#!/usr/bin/python3
"""Create and run a runner-specific, descriptor-held LidSwitch build authority.

This program belongs to the orchestration checkout, not the candidate source
checkout.  It is deliberately invoked with ``/usr/bin/python3 -I -S -B`` by
the hosted workflow after that workflow has checked this file's fixed digest.
It never writes beneath the source checkout.  ``prepare`` verifies the exact
detached candidate source and creates an ignored, runner-private entry and
contract; ``build`` re-verifies those generated bytes before delegating to the
only permitted release build wrapper through descriptor number 30.
"""
from __future__ import annotations

import argparse
import fcntl
import hashlib
import json
import os
import re
import stat
import subprocess
import sys
import tempfile
from pathlib import Path

EX_IOERR = 74
LIMIT = 8 * 1024 * 1024
SOURCE_COMMIT = "6200836869591acb4bf65edb825eb62e84b56f87"
SOURCE_TREE = "d86650eccfe3326fc968fc855a07a1e3d06aaf57"
WRAPPER_SHA256 = "7b14608282edca96003effaf1c5c70426368aa7e4a32d5a3c9b6550032e3e260"
WRAPPER_PATH = "script/run_swift_build_safely.sh"
ROLES = {
    "wrapper": (30, WRAPPER_PATH),
    "common": (31, "script/swift_sandbox_common.sh"),
    "envelope": (32, "script/live_state_envelope.sh"),
    "profile": (33, "script/swift_test_sandbox.sb.in"),
    "safe_file": (34, "script/safe_file_capability.py"),
    "supervisor": (35, "script/safe_process_supervisor.py"),
    "source_manifest": (36, "script/source_snapshot_manifest.jsonl"),
    # The packaging closure is never executed by pathname from the source
    # checkout.  These are copied from verified descriptors into a fresh
    # private directory before Python imports them.
    "capture_package": (42, "script/capture_immutable_build_envelope.py"),
    "assemble_package": (43, "script/assemble_manual_adhoc_candidate.py"),
    "candidate_core": (44, "script/immutable_candidate_core.py"),
    "build_manifest": (45, "script/build_immutable_candidate.py"),
    "package_manifest": (46, "script/package_immutable_candidate.py"),
    "validate_candidate": (47, "script/validate_immutable_candidate.py"),
    "validate_dmg": (48, "script/validate_immutable_dmg.py"),
    "release_identity": (49, "Resources/LidSwitchReleaseIdentity.json"),
    "icon": (50, "Resources/LidSwitch.icns"),
}
FD_MAP = {name: fd for name, (fd, _path) in ROLES.items()} | {
    "repo_root": 37, "control_root": 38, "execution_root": 39,
    "terminal_pipe": 40, "startup_gate": 41,
}
NAME = re.compile(r"[A-Za-z0-9._+-]{1,128}\Z")


class Denied(RuntimeError):
    pass


def deny(reason: str) -> None:
    raise Denied(reason)


def canonical(value: object) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8") + b"\n"


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def read_fd(fd: int, limit: int = LIMIT, *, single_link: bool = True) -> bytes:
    before = os.fstat(fd)
    if not stat.S_ISREG(before.st_mode) or (single_link and before.st_nlink != 1) or before.st_nlink < 1 or not 0 < before.st_size <= limit:
        deny("unsafe-regular-descriptor")
    os.lseek(fd, 0, os.SEEK_SET)
    data = bytearray()
    while len(data) < before.st_size:
        try:
            piece = os.read(fd, min(131072, before.st_size - len(data)))
        except InterruptedError:
            continue
        if not piece:
            deny("short-regular-descriptor")
        data.extend(piece)
    if os.read(fd, 1) or identity(os.fstat(fd)) != identity(before):
        deny("drift-regular-descriptor")
    return bytes(data)


def identity(info: os.stat_result) -> tuple[int, int, int, int, int, int, int]:
    return (info.st_dev, info.st_ino, info.st_uid, info.st_gid, stat.S_IMODE(info.st_mode), info.st_nlink, info.st_size)


def descriptor(path: Path, *, system: bool = False, maximum: int = LIMIT) -> dict[str, object]:
    if path.is_symlink():
        deny("symlinked-descriptor: " + str(path))
    fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC)
    try:
        before = os.fstat(fd)
        if not stat.S_ISREG(before.st_mode) or (not system and before.st_nlink != 1) or before.st_nlink < 1 or before.st_size <= 0:
            deny("unsafe-descriptor: " + str(path))
        if before.st_mode & 0o022:
            deny("writable-descriptor: " + str(path))
        if system and (before.st_uid != 0 or before.st_gid != 0):
            deny("unowned-system-descriptor: " + str(path))
        data = read_fd(fd, maximum, single_link=not system)
        after = os.fstat(fd)
        if identity(before) != identity(after):
            deny("drift-descriptor: " + str(path))
        return {"path": str(path), "dev": before.st_dev, "inode": before.st_ino,
                "uid": before.st_uid, "gid": before.st_gid, "mode": stat.S_IMODE(before.st_mode),
                "nlink": before.st_nlink, "size": before.st_size, "sha256": sha256(data)}
    finally:
        os.close(fd)


def checked_directory(path: Path) -> dict[str, int]:
    if path.is_symlink():
        deny("symlinked-directory: " + str(path))
    fd = os.open(path, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC)
    try:
        info = os.fstat(fd)
        if not stat.S_ISDIR(info.st_mode) or info.st_nlink < 2 or info.st_mode & 0o022:
            deny("unsafe-directory: " + str(path))
        return {"dev": info.st_dev, "inode": info.st_ino, "uid": info.st_uid, "gid": info.st_gid,
                "mode": stat.S_IMODE(info.st_mode), "nlink": info.st_nlink}
    finally:
        os.close(fd)


def git(source: Path, *args: str) -> str:
    result = subprocess.run(["/usr/bin/git", "-C", str(source), *args], stdin=subprocess.DEVNULL,
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
                            env={"PATH": "/usr/bin:/bin:/usr/sbin:/sbin", "LC_ALL": "C"}, check=False)
    if result.returncode != 0:
        deny("git-verification-failed: " + args[0])
    return result.stdout


def under(child: Path, parent: Path) -> bool:
    try:
        child.resolve().relative_to(parent.resolve())
        return True
    except ValueError:
        return False


def tree_digest(fd: int, prefix: str) -> str:
    digest = hashlib.sha256()
    before = identity(os.fstat(fd))
    for child in sorted(os.listdir(fd)):
        if child.startswith(".") or NAME.fullmatch(child) is None:
            deny("unsafe-manifest-tree-name")
        cfd = os.open(child, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC, dir_fd=fd)
        try:
            meta = os.fstat(cfd)
            path = prefix + "/" + child
            if stat.S_ISDIR(meta.st_mode):
                digest.update(bytes.fromhex(tree_digest(cfd, path)))
            elif stat.S_ISREG(meta.st_mode) and meta.st_nlink == 1 and not meta.st_mode & 0o022:
                payload = read_fd(cfd, 256 * 1024 * 1024)
                digest.update((path + "|" + str(meta.st_size) + "|" + sha256(payload) + "\n").encode("utf-8"))
            else:
                deny("unsafe-manifest-tree-node")
        finally:
            os.close(cfd)
    if identity(os.fstat(fd)) != before:
        deny("drift-manifest-tree")
    # The source manifest's tree scheme is the hash of its complete textual
    # member record stream, not a recursive composition of child digests.
    # Recompute that stream directly so this function cannot silently accept
    # a different tree representation.
    stream = hashlib.sha256()
    def visit(directory_fd: int, name: str) -> None:
        start = identity(os.fstat(directory_fd))
        for leaf in sorted(os.listdir(directory_fd)):
            if leaf.startswith(".") or NAME.fullmatch(leaf) is None:
                deny("unsafe-manifest-tree-name")
            leaf_fd = os.open(leaf, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC, dir_fd=directory_fd)
            try:
                leaf_meta = os.fstat(leaf_fd)
                leaf_path = name + "/" + leaf
                if stat.S_ISDIR(leaf_meta.st_mode):
                    visit(leaf_fd, leaf_path)
                elif stat.S_ISREG(leaf_meta.st_mode) and leaf_meta.st_nlink == 1 and not leaf_meta.st_mode & 0o022:
                    payload = read_fd(leaf_fd, 256 * 1024 * 1024)
                    stream.update((leaf_path + "|" + str(leaf_meta.st_size) + "|" + sha256(payload) + "\n").encode("utf-8"))
                else:
                    deny("unsafe-manifest-tree-node")
            finally:
                os.close(leaf_fd)
        if identity(os.fstat(directory_fd)) != start:
            deny("drift-manifest-tree")
    visit(fd, prefix)
    return stream.hexdigest()


def verify_manifest(source: Path) -> tuple[dict[str, object], str]:
    manifest_path = source / "script/source_snapshot_manifest.jsonl"
    raw = descriptor(manifest_path, maximum=1024 * 1024)
    fd = os.open(manifest_path, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC)
    root_fd = os.open(source, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC)
    try:
        payload = read_fd(fd, 1024 * 1024)
        lines = payload.decode("utf-8", "strict").splitlines()
        rows = [json.loads(line) for line in lines]
        if not rows or any(canonical(row).rstrip(b"\n").decode("utf-8") != line for row, line in zip(rows, lines)):
            deny("noncanonical-source-manifest")
        paths = [row.get("path") for row in rows]
        if paths != sorted(paths) or len(paths) != len(set(paths)):
            deny("unsafe-source-manifest-inventory")
        for row in rows:
            if set(row) - {"schema", "type", "path", "mode", "size", "sha256"} or row.get("schema") != "lidswitch-source-manifest-v1":
                deny("unsafe-source-manifest-row")
            relative = row.get("path")
            if not isinstance(relative, str) or relative.startswith("/") or ".." in relative.split("/"):
                deny("unsafe-source-manifest-path")
            entry_fd = os.open(relative, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC, dir_fd=root_fd)
            try:
                info = os.fstat(entry_fd)
                if row.get("type") == "file":
                    payload_entry = read_fd(entry_fd, 256 * 1024 * 1024)
                    if (not stat.S_ISREG(info.st_mode) or info.st_size != row.get("size") or
                            stat.S_IMODE(info.st_mode) != row.get("mode") or sha256(payload_entry) != row.get("sha256")):
                        deny("source-manifest-file-mismatch: " + relative)
                elif row.get("type") == "tree":
                    if not stat.S_ISDIR(info.st_mode) or tree_digest(entry_fd, relative) != row.get("sha256"):
                        deny("source-manifest-tree-mismatch: " + relative)
                else:
                    deny("unsafe-source-manifest-row")
            finally:
                os.close(entry_fd)
        return raw, sha256(payload)
    finally:
        os.close(root_fd)
        os.close(fd)


ENTRY = r'''#!/usr/bin/python3
import argparse, fcntl, hashlib, json, os, stat, sys, tempfile
EX=74; ROLES={"wrapper":30,"common":31,"envelope":32,"profile":33,"safe_file":34,"supervisor":35,"source_manifest":36,"capture_package":42,"assemble_package":43,"candidate_core":44,"build_manifest":45,"package_manifest":46,"validate_candidate":47,"validate_dmg":48,"release_identity":49,"icon":50}
def die(): raise SystemExit(EX)
def ident(s): return (s.st_dev,s.st_ino,s.st_uid,s.st_gid,stat.S_IMODE(s.st_mode),s.st_nlink,s.st_size)
def read(fd,limit=8*1024*1024):
 try:
  before=os.fstat(fd)
  if not stat.S_ISREG(before.st_mode) or before.st_nlink!=1 or not 0<before.st_size<=limit: die()
  os.lseek(fd,0,os.SEEK_SET); out=bytearray()
  while len(out)<before.st_size:
   try: p=os.read(fd,min(131072,before.st_size-len(out)))
   except InterruptedError: continue
   if not p: die()
   out.extend(p)
  if os.read(fd,1) or ident(os.fstat(fd))!=ident(before): die()
  return bytes(out)
 except OSError: die()
def dup(fd):
 try: return fcntl.fcntl(fd,fcntl.F_DUPFD_CLOEXEC,64)
 except OSError: die()
def close(fd):
 try: os.close(fd)
 except OSError: die()
def role(root,rel,want,dirs):
 if not isinstance(rel,str) or rel.startswith("/") or ".." in rel.split("/"): die()
 parent=root; opened=[]
 try:
  parts=rel.split("/")
  for part in parts[:-1]:
   parent=os.open(part,os.O_RDONLY|os.O_DIRECTORY|os.O_NOFOLLOW|os.O_CLOEXEC,dir_fd=parent); opened.append(parent)
   meta=os.fstat(parent); expected=dirs.get(part)
   if not isinstance(expected,dict) or ident(meta)[:-1] != tuple(expected.get(k) for k in ("dev","inode","uid","gid","mode","nlink")): die()
  fd=os.open(parts[-1],os.O_RDONLY|os.O_NOFOLLOW|os.O_CLOEXEC,dir_fd=parent)
  raw=read(fd); meta=os.fstat(fd)
  if ident(meta)+(hashlib.sha256(raw).hexdigest(),)!=tuple(want.get(k) for k in ("dev","inode","uid","gid","mode","nlink","size","sha256")): die()
  os.lseek(fd,0,os.SEEK_SET); return fd
 except OSError: die()
 finally:
  for item in opened:
   try: os.close(item)
   except OSError: die()
def private(prefix):
 try:
  p=tempfile.mkdtemp(prefix=prefix,dir="/private/tmp"); fd=os.open(p,os.O_RDONLY|os.O_DIRECTORY|os.O_NOFOLLOW|os.O_CLOEXEC); s=os.fstat(fd)
  if not stat.S_ISDIR(s.st_mode) or s.st_uid!=os.getuid() or stat.S_IMODE(s.st_mode)!=0o700 or s.st_nlink<2: die()
  os.fchown(fd,-1,os.getgid()); return p,dup(fd)
 except OSError: die()
 finally:
  try: os.close(fd)
  except BaseException: pass
def bash(spec):
 try:
  fd=os.open("/bin/bash",os.O_RDONLY|os.O_NOFOLLOW|os.O_CLOEXEC); raw=read(fd,16*1024*1024); s=os.fstat(fd); os.close(fd)
  if ident(s)+(hashlib.sha256(raw).hexdigest(),)!=tuple(spec.get(k) for k in ("dev","inode","uid","gid","mode","nlink","size","sha256")): die()
 except OSError: die()
def main():
 p=argparse.ArgumentParser(allow_abbrev=False); p.add_argument("--repo",required=True); p.add_argument("--contract-fd",required=True,type=int); p.add_argument("--contract-sha256",required=True); p.add_argument("--contract-size",required=True,type=int); p.add_argument("--hosted-receipt",required=True); p.add_argument("--release-candidate",action="store_true"); p.add_argument("wrapper",choices=("build",)); p.add_argument("args",nargs=argparse.REMAINDER); a=p.parse_args()
 if not a.release_candidate or len(a.contract_sha256)!=64 or a.contract_size<=0: die()
 raw=read(a.contract_fd)
 if len(raw)!=a.contract_size or hashlib.sha256(raw).hexdigest()!=a.contract_sha256: die()
 try: c=json.loads(raw.decode("utf-8"))
 except BaseException: die()
 if json.dumps(c,sort_keys=True,separators=(",",":")).encode()+b"\\n"!=raw or c.get("schema")!="lidswitch-hosted-held-contract-v1" or c.get("fd_map")!={**ROLES,"repo_root":37,"control_root":38,"execution_root":39,"terminal_pipe":40,"startup_gate":41}: die()
 if set(c.get("roles",{}))!=set(ROLES) or c.get("roles",{}).get("wrapper",{}).get("path")!="script/run_swift_build_safely.sh": die()
 close(a.contract_fd); root=os.open(a.repo,os.O_RDONLY|os.O_DIRECTORY|os.O_NOFOLLOW|os.O_CLOEXEC); rs=os.fstat(root)
 if not stat.S_ISDIR(rs.st_mode) or rs.st_mode&0o022: die()
 fds={n:dup(role(root,c["roles"][n]["path"],c["roles"][n],c.get("directories",{}))) for n in ROLES}; control,cfd=private("lidswitch-envelope."); execution,xfd=private("lidswitch-swift.")
 gr,gw=os.pipe(); tr,tw=os.pipe(); bash(c["bash"])
 child={30:fds["wrapper"],31:fds["common"],32:fds["envelope"],33:fds["profile"],34:fds["safe_file"],35:fds["supervisor"],36:fds["source_manifest"],37:root,38:cfd,39:xfd,40:tw,41:gr}
 for fd in child.values(): os.lseek(fd,0,os.SEEK_SET) if fd in fds.values() else None
 acts=[(os.POSIX_SPAWN_OPEN,0,"/dev/null",os.O_RDONLY,0)]+[(os.POSIX_SPAWN_DUP2,v,k) for k,v in child.items()]+[(os.POSIX_SPAWN_CLOSE,v) for v in set(child.values())]
 env={"PATH":"/usr/bin:/bin:/usr/sbin:/sbin","LC_ALL":"C","LIDSWITCH_HELD_ENTRY":"v1","LIDSWITCH_HELD_FD_MAP":"30,31,32,33,34,35,36,37,38,39,40,41","LIDSWITCH_HELD_REPO_ROOT":a.repo,"LIDSWITCH_HELD_CONTROL_ROOT":control,"LIDSWITCH_HELD_EXECUTION_ROOT":execution,"LIDSWITCH_HELD_RELEASE_CANDIDATE":"v1"}
 pid=os.posix_spawn("/bin/bash",["/bin/bash","-p","--","/dev/fd/30",*a.args],env,file_actions=acts); close(gr); os.write(gw,b"R"); close(gw); close(tw); _,status=os.waitpid(pid,0); bash(c["bash"])
 for n in ROLES:
  q=role(root,c["roles"][n]["path"],c["roles"][n],c.get("directories",{})); close(q)
 receipt=read(os.open("live-state-retained.receipt",os.O_RDONLY|os.O_NOFOLLOW|os.O_CLOEXEC,dir_fd=cfd),65536); rc=os.WEXITSTATUS(status) if os.WIFEXITED(status) else EX
 try:
  rows={};
  for line in receipt.decode("utf-8","strict").splitlines():
   k,v=line.split("=",1)
   if not k or k in rows: die()
   rows[k]=v
  if rows.get("schema")!="3" or rows.get("terminal")!="idle-uninstalled" or rows.get("kernel")!="25E246" or rows.get("child_command_exit")!="0" or rows.get("wrapper_exit")!="0" or rows.get("outcome")!="preserved" or rc!=0: die()
  def snap(names,want):
   for name in names:
    try: raw=read(os.open(name,os.O_RDONLY|os.O_NOFOLLOW|os.O_CLOEXEC,dir_fd=cfd),65536)
    except OSError: continue
    if hashlib.sha256(raw).hexdigest()!=want: continue
    vals={}
    for line in raw.decode("utf-8","strict").splitlines():
     k,v=line.split("=",1)
     if not k or k in vals: die()
     vals[k]=v
    if vals.get("host_class")!="idle-uninstalled" or vals.get("kernel_build")!="25E246": die()
    return raw
   die()
  pre=snap(("live-preflight.kv","live-preflight-initial.kv"),rows.get("preflight_sha256","")); post=snap(("live-postflight.kv",),rows.get("postflight_sha256",""))
  destination=os.path.dirname(a.hosted_receipt)
  def save(name,data):
   fd=os.open(os.path.join(destination,name),os.O_WRONLY|os.O_CREAT|os.O_EXCL|os.O_NOFOLLOW|os.O_CLOEXEC,0o400)
   try: os.write(fd,data); os.fsync(fd)
   finally: os.close(fd)
  save("live-state-retained.receipt",receipt); save("preflight-state.snapshot",pre); save("postflight-state.snapshot",post)
 except BaseException: die()
 try:
  with open(a.hosted_receipt,"xb") as out: out.write(json.dumps({"schema":"lidswitch-hosted-live-envelope-v2","receipt_sha256":hashlib.sha256(receipt).hexdigest(),"preflight_sha256":hashlib.sha256(pre).hexdigest(),"postflight_sha256":hashlib.sha256(post).hexdigest(),"wrapper_exit":rc},sort_keys=True,separators=(",",":")).encode()+b"\\n")
 except OSError: die()
 os.write(2,("LIDSWITCH_HOSTED_HELD_RECEIPT\\nschema=1\\nreceipt_sha256="+hashlib.sha256(receipt).hexdigest()+"\\nwrapper_exit="+str(rc)+"\\n").encode()); raise SystemExit(rc)
if __name__=="__main__":
 try: main()
 except SystemExit: raise
 except BaseException: die()
'''


def policy(path: Path) -> dict[str, object]:
    raw = descriptor(path, maximum=1024 * 1024)
    value = json.loads(Path(path).read_text("utf-8"))
    if canonical(value) != Path(path).read_bytes() or value.get("schema") != "lidswitch-hosted-runner-policy-v1":
        deny("invalid-hosted-policy")
    source = value.get("source")
    if source != {"commit": SOURCE_COMMIT, "tree": SOURCE_TREE, "wrapper_sha256": WRAPPER_SHA256}:
        deny("policy-source-binding-mismatch")
    return {"descriptor": raw, "value": value}


def prepare(source: Path, authority: Path, policy_path: Path) -> dict[str, object]:
    pol = policy(policy_path)
    source = source.resolve(strict=True)
    authority = authority.resolve(strict=False)
    if under(authority, source):
        deny("authority-must-remain-outside-source")
    if authority.exists() or authority.is_symlink():
        deny("authority-must-not-exist")
    root = checked_directory(source)
    if git(source, "rev-parse", "HEAD").strip() != SOURCE_COMMIT or git(source, "rev-parse", "HEAD^{tree}").strip() != SOURCE_TREE:
        deny("source-commit-or-tree-mismatch")
    if git(source, "status", "--porcelain=v1", "--untracked-files=all"):
        deny("source-checkout-not-clean")
    manifest, manifest_sha = verify_manifest(source)
    if manifest_sha != pol["value"]["source_manifest_sha256"]:
        deny("source-manifest-digest-mismatch")
    roles: dict[str, dict[str, object]] = {}
    directories: dict[str, dict[str, int]] = {}
    for name, (_fd, relative) in ROLES.items():
        roles[name] = descriptor(source / relative, maximum=256 * 1024 * 1024)
        roles[name]["path"] = relative
        for component in relative.split("/")[:-1]:
            directories.setdefault(component, checked_directory(source / component))
    if roles["wrapper"]["sha256"] != WRAPPER_SHA256:
        deny("unchanged-wrapper-digest-mismatch")
    bash = descriptor(Path("/bin/bash"), system=True, maximum=16 * 1024 * 1024)
    python = descriptor(Path("/usr/bin/python3"), system=True, maximum=64 * 1024 * 1024)
    swift = descriptor(Path("/Library/Developer/CommandLineTools/usr/bin/swift-frontend"), system=True, maximum=128 * 1024 * 1024)
    sdk = checked_directory(Path("/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"))
    authority.mkdir(mode=0o700, parents=False)
    info = checked_directory(authority)
    if stat.S_IMODE(os.stat(authority, follow_symlinks=False).st_mode) != 0o700:
        deny("unsafe-authority-root")
    contract = {"schema": "lidswitch-hosted-held-contract-v1", "fd_map": FD_MAP, "roles": roles,
                "directories": directories, "bash": bash, "source_manifest": manifest["sha256"]}
    contract_bytes = canonical(contract)
    entry = authority / "hosted-held-entry.py"
    contract_path = authority / "hosted-held-contract.json"
    ledger_path = authority / "hosted-authority-ledger.json"
    for path, data, mode in ((entry, ENTRY.encode("utf-8"), 0o500), (contract_path, contract_bytes, 0o400)):
        fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW | os.O_CLOEXEC, mode)
        try:
            os.write(fd, data); os.fsync(fd)
        finally:
            os.close(fd)
    ledger = {"schema": "lidswitch-hosted-authority-ledger-v1", "policy": pol["descriptor"],
              "source": {"commit": SOURCE_COMMIT, "tree": SOURCE_TREE, "root": root,
                         "manifest_sha256": manifest_sha, "manifest_descriptor": manifest},
              "system": {"python": python, "bash": bash, "swift_frontend": swift, "sdk_root": sdk,
                         "developer_dir": "/Library/Developer/CommandLineTools"}, "wrapper_sha256": WRAPPER_SHA256,
              "generated": {"entry": descriptor(entry), "contract": descriptor(contract_path), "root": info}}
    fd = os.open(ledger_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW | os.O_CLOEXEC, 0o400)
    try:
        data = canonical(ledger); os.write(fd, data); os.fsync(fd)
    finally:
        os.close(fd)
    # This receipt is deliberately emitted outside the generated ledger: the
    # next workflow step must carry these values as explicit build inputs.
    return {"schema": "lidswitch-hosted-prepare-v2", "authority": str(authority),
            "ledger": descriptor(ledger_path), "entry": descriptor(entry),
            "contract": descriptor(contract_path), "source_manifest_sha256": manifest_sha}


def _expected(descriptor_value: dict[str, object], name: str, sha: str, size: int) -> None:
    if not re.fullmatch(r"[0-9a-f]{64}", sha) or size <= 0 or descriptor_value.get("sha256") != sha or descriptor_value.get("size") != size:
        deny("external-expected-" + name + "-mismatch")


def build(source: Path, authority: Path, policy_path: Path, expected: dict[str, tuple[str, int]]) -> dict[str, object]:
    prepared = prepare_recheck(source, authority, policy_path)
    ledger = prepared["ledger"]
    generated = ledger["generated"]
    entry = authority / "hosted-held-entry.py"
    contract = authority / "hosted-held-contract.json"
    for name, path in (("entry", entry), ("contract", contract)):
        observed = descriptor(path)
        if observed != generated[name]:
            deny("generated-authority-drift: " + name)
    _expected(descriptor(ledger_path := authority / "hosted-authority-ledger.json"), "ledger", *expected["ledger"])
    _expected(descriptor(entry), "entry", *expected["entry"])
    _expected(descriptor(contract), "contract", *expected["contract"])
    contract_fd = os.open(contract, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC)
    entry_fd = os.open(entry, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC)
    try:
        # /dev/fd is backed by the descriptor just verified above; a mutable
        # authority pathname is not an execution authority.
        run = subprocess.run(["/usr/bin/python3", "-I", "-S", "-B", "/dev/fd/" + str(entry_fd), "--repo", str(source),
                              "--contract-fd", str(contract_fd), "--contract-sha256", str(generated["contract"]["sha256"]),
                              "--contract-size", str(generated["contract"]["size"]), "--hosted-receipt", str(authority / "hosted-live-envelope.json"), "--release-candidate", "build",
                              "--print-bin-path"],
                             stdin=subprocess.DEVNULL, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
                             pass_fds=(contract_fd, entry_fd), env={"PATH": "/usr/bin:/bin:/usr/sbin:/sbin", "LC_ALL": "C", "DEVELOPER_DIR": "/Library/Developer/CommandLineTools"}, check=False)
    finally:
        os.close(contract_fd)
        os.close(entry_fd)
    if run.returncode != 0:
        sys.stderr.write(run.stderr)
        deny("held-wrapper-failed: " + str(run.returncode))
    release_output = run.stdout.strip()
    if not release_output.startswith("/private/tmp/lidswitch-swift.") or "/release-output" not in release_output:
        deny("held-release-output-path-invalid")
    # Recheck the candidate after the wrapper and bind the actual retained
    # host-state proof into the build receipt rather than a hash-only claim.
    prepare_recheck(source, authority, policy_path)
    retained = {name: descriptor(authority / name, maximum=65536) for name in ("live-state-retained.receipt", "preflight-state.snapshot", "postflight-state.snapshot", "hosted-live-envelope.json")}
    print(canonical({"schema": "lidswitch-hosted-build-v2", "source": ledger["source"], "generated": generated,
                     "ledger": descriptor(ledger_path), "entry": descriptor(entry), "contract": descriptor(contract),
                     "retained": retained, "release_output": release_output}).decode(), end="")
    return {"release_output": release_output}


def prepare_recheck(source: Path, authority: Path, policy_path: Path) -> dict[str, object]:
    policy(policy_path)
    ledger_path = authority / "hosted-authority-ledger.json"
    observed = descriptor(ledger_path, maximum=1024 * 1024)
    raw = Path(ledger_path).read_bytes()
    ledger = json.loads(raw.decode("utf-8"))
    if canonical(ledger) != raw or ledger.get("schema") != "lidswitch-hosted-authority-ledger-v1":
        deny("invalid-authority-ledger")
    if ledger.get("source", {}).get("commit") != SOURCE_COMMIT or ledger.get("source", {}).get("tree") != SOURCE_TREE:
        deny("authority-source-binding-mismatch")
    if git(source, "rev-parse", "HEAD").strip() != SOURCE_COMMIT or git(source, "rev-parse", "HEAD^{tree}").strip() != SOURCE_TREE:
        deny("source-drift-before-build")
    if git(source, "status", "--porcelain=v1", "--untracked-files=all"):
        deny("source-not-clean-before-build")
    _manifest, manifest_sha = verify_manifest(source)
    if manifest_sha != ledger["source"]["manifest_sha256"]:
        deny("source-manifest-drift-before-build")
    if descriptor(Path("/bin/bash"), system=True, maximum=16 * 1024 * 1024) != ledger["system"]["bash"]:
        deny("bash-drift-before-build")
    if descriptor(Path("/usr/bin/python3"), system=True, maximum=64 * 1024 * 1024) != ledger["system"]["python"]:
        deny("python-drift-before-build")
    if descriptor(Path("/Library/Developer/CommandLineTools/usr/bin/swift-frontend"), system=True, maximum=128 * 1024 * 1024) != ledger["system"]["swift_frontend"]:
        deny("swift-frontend-drift-before-build")
    if checked_directory(Path("/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk")) != ledger["system"]["sdk_root"]:
        deny("sdk-root-drift-before-build")
    return {"ledger": ledger}


def _copy_verified(source: Path, relative: str, expected: dict[str, object], target: Path) -> None:
    """Copy a descriptor-verified source leaf into private held packaging."""
    fd = os.open(source / relative, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC)
    try:
        info = os.fstat(fd)
        data = read_fd(fd, 256 * 1024 * 1024)
        actual = {"path": relative, "dev": info.st_dev, "inode": info.st_ino, "uid": info.st_uid, "gid": info.st_gid, "mode": stat.S_IMODE(info.st_mode), "nlink": info.st_nlink, "size": info.st_size, "sha256": sha256(data)}
        if actual != expected:
            deny("packaging-role-drift: " + relative)
    finally:
        os.close(fd)
    target.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    fd = os.open(target, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW | os.O_CLOEXEC, 0o500)
    try:
        os.write(fd, data)
        os.fsync(fd)
    finally:
        os.close(fd)
    if descriptor(target, maximum=256 * 1024 * 1024)["sha256"] != expected["sha256"]:
        deny("held-packaging-copy-drift: " + relative)


def _read_authority_descriptor(path: Path, expected: dict[str, object]) -> bytes:
    fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC)
    try:
        info = os.fstat(fd)
        data = read_fd(fd, 1024 * 1024)
        actual = {"path": str(path), "dev": info.st_dev, "inode": info.st_ino, "uid": info.st_uid, "gid": info.st_gid, "mode": stat.S_IMODE(info.st_mode), "nlink": info.st_nlink, "size": info.st_size, "sha256": sha256(data)}
        if actual != expected:
            deny("packaging-contract-authority-drift")
        return data
    finally:
        os.close(fd)


def package(source: Path, authority: Path, policy_path: Path, release_output: Path, package_parent: Path) -> dict[str, object]:
    prepared = prepare_recheck(source, authority, policy_path)
    contract_path = authority / "hosted-held-contract.json"
    raw_contract = _read_authority_descriptor(contract_path, prepared["ledger"]["generated"]["contract"])
    contract = json.loads(raw_contract.decode("utf-8"))
    if canonical(contract) != raw_contract or contract.get("source_manifest") != prepared["ledger"]["source"]["manifest_descriptor"]["sha256"]:
        deny("packaging-contract-invalid")
    held = package_parent / "held-packaging"
    if held.exists() or held.is_symlink() or package_parent.is_symlink():
        deny("unsafe-held-packaging-root")
    held.mkdir(mode=0o700)
    names = {"capture_package": "capture_immutable_build_envelope.py", "assemble_package": "assemble_manual_adhoc_candidate.py", "candidate_core": "immutable_candidate_core.py", "build_manifest": "build_immutable_candidate.py", "package_manifest": "package_immutable_candidate.py", "validate_candidate": "validate_immutable_candidate.py", "validate_dmg": "validate_immutable_dmg.py", "source_manifest": "source_snapshot_manifest.jsonl", "wrapper": "run_swift_build_safely.sh"}
    for role, name in names.items():
        _copy_verified(source, contract["roles"][role]["path"], contract["roles"][role], held / "script" / name)
    for role, name in (("release_identity", "LidSwitchReleaseIdentity.json"), ("icon", "LidSwitch.icns")):
        _copy_verified(source, contract["roles"][role]["path"], contract["roles"][role], held / "Resources" / name)
    envelope = package_parent / "build-envelope.json"
    command = ["/usr/bin/python3", "-I", "-S", "-B", str(held / "script/capture_immutable_build_envelope.py"), "--source-commit", SOURCE_COMMIT, "--source-manifest", str(held / "script/source_snapshot_manifest.jsonl"), "--held-build-wrapper", str(held / "script/run_swift_build_safely.sh"), "--swift", "/Library/Developer/CommandLineTools/usr/bin/swift", "--release-output", str(release_output), "--output", str(envelope)]
    first = subprocess.run(command, stdin=subprocess.DEVNULL, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, env={"PATH": "/usr/bin:/bin:/usr/sbin:/sbin", "LC_ALL": "C", "DEVELOPER_DIR": "/Library/Developer/CommandLineTools"}, check=False)
    if first.returncode:
        sys.stderr.write(first.stderr); deny("held-packaging-capture-failed")
    candidate = package_parent / "candidate"
    second = subprocess.run(["/usr/bin/python3", "-I", "-S", "-B", str(held / "script/assemble_manual_adhoc_candidate.py"), "--envelope-receipt", str(envelope), "--release-output", str(release_output), "--output-root", str(candidate), "--icon", str(held / "Resources/LidSwitch.icns"), "--release-identity", str(held / "Resources/LidSwitchReleaseIdentity.json")], stdin=subprocess.DEVNULL, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, env={"PATH": "/usr/bin:/bin:/usr/sbin:/sbin", "LC_ALL": "C", "DEVELOPER_DIR": "/Library/Developer/CommandLineTools"}, check=False)
    if second.returncode:
        sys.stderr.write(second.stderr); deny("held-packaging-assemble-failed")
    prepare_recheck(source, authority, policy_path)
    return {"schema": "lidswitch-hosted-package-v1", "package_parent": str(package_parent), "candidate_root": str(candidate), "envelope": descriptor(envelope), "held_packaging": {name: descriptor(held / "script" / name) for name in names.values()}}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(allow_abbrev=False)
    sub = parser.add_subparsers(dest="command", required=True)
    for name in ("prepare", "build", "package"):
        item = sub.add_parser(name, allow_abbrev=False)
        item.add_argument("--source", required=True, type=Path)
        item.add_argument("--authority", required=True, type=Path)
        item.add_argument("--policy", required=True, type=Path)
        if name == "build":
            for role in ("ledger", "entry", "contract"):
                item.add_argument("--expected-" + role + "-sha256", required=True)
                item.add_argument("--expected-" + role + "-size", required=True, type=int)
        if name == "package":
            item.add_argument("--release-output", required=True, type=Path)
            item.add_argument("--package-parent", required=True, type=Path)
    args = parser.parse_args(argv)
    try:
        if args.command == "prepare":
            print(canonical(prepare(args.source, args.authority, args.policy)).decode(), end="")
        elif args.command == "build":
            build(args.source, args.authority, args.policy, {role: (getattr(args, "expected_" + role + "_sha256"), getattr(args, "expected_" + role + "_size")) for role in ("ledger", "entry", "contract")})
        else:
            print(canonical(package(args.source, args.authority, args.policy, args.release_output, args.package_parent)).decode(), end="")
        return 0
    except (Denied, OSError, UnicodeError, json.JSONDecodeError, KeyError, TypeError) as error:
        print("hosted-held-bootstrap-denied: " + str(error), file=sys.stderr)
        return EX_IOERR


if __name__ == "__main__":
    raise SystemExit(main())
