#!/usr/bin/python3
"""Create and run a runner-specific, descriptor-held LidSwitch build authority.

This program belongs to the orchestration checkout, not the candidate source
checkout.  It is deliberately invoked with ``/usr/bin/python3 -I -S -B`` by
the hosted workflow after that workflow has checked this file's fixed digest.
It never writes beneath the source checkout.  ``prepare`` verifies the exact
detached candidate source and creates an ignored, runner-private entry and
contract; ``build`` re-verifies those generated bytes before delegating to the
only permitted release build wrapper through descriptor number 30.
"""
from __future__ import annotations

import argparse
import ast
import fcntl
import hashlib
import json
import os
import re
import stat
import subprocess
import sys
import tempfile
from pathlib import Path

EX_IOERR = 74
LIMIT = 8 * 1024 * 1024
SOURCE_COMMIT = "6d095bba519a926a1b4131490cb3f6650fe9ab20"
SOURCE_TREE = "c7e942353a2976c2abf75c4494d009c133aca1eb"
WRAPPER_SHA256 = "7b14608282edca96003effaf1c5c70426368aa7e4a32d5a3c9b6550032e3e260"
WRAPPER_PATH = "script/run_swift_build_safely.sh"
REVIEWED_IMAGES = ["20260715.0248.1", "20260720.0258.1"]
ROLES = {
    "wrapper": (30, WRAPPER_PATH),
    "common": (31, "script/swift_sandbox_common.sh"),
    "envelope": (32, "script/live_state_envelope.sh"),
    "profile": (33, "script/swift_test_sandbox.sb.in"),
    "safe_file": (34, "script/safe_file_capability.py"),
    "supervisor": (35, "script/safe_process_supervisor.py"),
    "source_manifest": (36, "script/source_snapshot_manifest.jsonl"),
    # The packaging closure is never executed by pathname from the source
    # checkout.  These are copied from verified descriptors into a fresh
    # private directory before Python imports them.
    "capture_package": (42, "script/capture_immutable_build_envelope.py"),
    "assemble_package": (43, "script/assemble_manual_adhoc_candidate.py"),
    "candidate_core": (44, "script/immutable_candidate_core.py"),
    "build_manifest": (45, "script/build_immutable_candidate.py"),
    "package_manifest": (46, "script/package_immutable_candidate.py"),
    "validate_candidate": (47, "script/validate_immutable_candidate.py"),
    "validate_dmg": (48, "script/validate_immutable_dmg.py"),
    "release_identity": (49, "Resources/LidSwitchReleaseIdentity.json"),
    "icon": (50, "Resources/LidSwitch.icns"),
}
FD_MAP = {name: fd for name, (fd, _path) in ROLES.items()} | {
    "repo_root": 37, "control_root": 38, "execution_root": 39,
    "terminal_pipe": 40, "startup_gate": 41,
}
NAME = re.compile(r"[A-Za-z0-9._+-]{1,128}\Z")
PACKAGING_SCRIPTS = {
    "capture_package": "capture_immutable_build_envelope.py",
    "assemble_package": "assemble_manual_adhoc_candidate.py",
    "candidate_core": "immutable_candidate_core.py",
    "build_manifest": "build_immutable_candidate.py",
    "package_manifest": "package_immutable_candidate.py",
    "validate_candidate": "validate_immutable_candidate.py",
    "validate_dmg": "validate_immutable_dmg.py",
    "source_manifest": "source_snapshot_manifest.jsonl",
    "wrapper": "run_swift_build_safely.sh",
}
PACKAGING_RESOURCES = {
    "release_identity": "LidSwitchReleaseIdentity.json",
    "icon": "LidSwitch.icns",
}
PACKAGING_ENTRYPOINTS = {
    "capture_immutable_build_envelope.py",
    "assemble_manual_adhoc_candidate.py",
    "run_swift_build_safely.sh",
}
AUTHORITY_INITIAL_FILES = frozenset({"hosted-held-entry.py", "hosted-held-contract.json", "hosted-authority-ledger.json"})
AUTHORITY_COMPLETE_FILES = AUTHORITY_INITIAL_FILES | frozenset({"live-state-retained.receipt", "preflight-state.snapshot", "postflight-state.snapshot", "preflight.pmset-assertions", "postflight.pmset-assertions", "hosted-live-envelope.json"})
PACKAGING_ENV = {
    "PATH": "/usr/bin:/bin:/usr/sbin:/sbin",
    "LC_ALL": "C",
    "DEVELOPER_DIR": "/Library/Developer/CommandLineTools",
}
# The child starts in / and does not inherit PYTHONPATH.  This small launcher
# installs only the sealed script directory and checks that every local module
# imported by the packaging programs came from that directory.  The packaging
# boundary is a bounded fresh-runner, same-UID threat model: inventories detect
# pre/post-spawn replacement, not an adversary able to replace a leaf after the
# final check while CPython is already importing it by pathname.
PACKAGING_PYTHON_BOOTSTRAP = r'''import json, os, runpy, sys, sysconfig
entry, script_root, allowed_json = sys.argv[1:4]
entry_args = sys.argv[4:]
allowed = set(json.loads(allowed_json))
script_root = os.path.realpath(script_root)
if os.getcwd() != "/" or not os.path.isabs(entry) or os.path.dirname(os.path.realpath(entry)) != script_root:
    raise SystemExit(74)
stdlib = os.path.realpath(sysconfig.get_path("stdlib"))
workspace = os.path.realpath(os.environ.get("GITHUB_WORKSPACE", "/__no_workspace__"))
def trusted_stdlib(path):
    if not isinstance(path, str) or not path:
        return False
    resolved = os.path.realpath(path)
    parts = set(resolved.split(os.sep))
    return (os.path.isabs(path) and resolved != os.path.realpath(os.getcwd())
            and "site-packages" not in parts and "dist-packages" not in parts
            and not (resolved == workspace or resolved.startswith(workspace + os.sep))
            and (resolved == stdlib or resolved.startswith(stdlib + os.sep)))
stdlib_paths = []
for candidate in sys.path:
    if trusted_stdlib(candidate) and candidate not in stdlib_paths:
        stdlib_paths.append(candidate)
if not stdlib_paths:
    raise SystemExit(74)
sys.path[:] = [script_root, *stdlib_paths]
sys.argv[:] = [entry, *entry_args]
exit_code = 0
try:
    runpy.run_path(entry, run_name="__main__")
except SystemExit as error:
    exit_code = error.code if isinstance(error.code, int) else (0 if error.code is None else 1)
for module_name in allowed:
    module = sys.modules.get(module_name)
    if module is None:
        continue
    module_file = getattr(module, "__file__", None)
    if not isinstance(module_file, str) or os.path.dirname(os.path.realpath(module_file)) != script_root:
        raise SystemExit(74)
raise SystemExit(exit_code)
'''


class Denied(RuntimeError):
    pass


def deny(reason: str) -> None:
    raise Denied(reason)


def canonical(value: object) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8") + b"\n"


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def read_fd(fd: int, limit: int = LIMIT, *, single_link: bool = True) -> bytes:
    before = os.fstat(fd)
    if not stat.S_ISREG(before.st_mode) or (single_link and before.st_nlink != 1) or before.st_nlink < 1 or not 0 < before.st_size <= limit:
        deny("unsafe-regular-descriptor")
    os.lseek(fd, 0, os.SEEK_SET)
    data = bytearray()
    while len(data) < before.st_size:
        try:
            piece = os.read(fd, min(131072, before.st_size - len(data)))
        except InterruptedError:
            continue
        if not piece:
            deny("short-regular-descriptor")
        data.extend(piece)
    if os.read(fd, 1) or identity(os.fstat(fd)) != identity(before):
        deny("drift-regular-descriptor")
    return bytes(data)


def identity(info: os.stat_result) -> tuple[int, int, int, int, int, int, int]:
    return (info.st_dev, info.st_ino, info.st_uid, info.st_gid, stat.S_IMODE(info.st_mode), info.st_nlink, info.st_size)


def descriptor(path: Path, *, system: bool = False, maximum: int = LIMIT) -> dict[str, object]:
    if path.is_symlink():
        deny("symlinked-descriptor: " + str(path))
    fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC)
    try:
        before = os.fstat(fd)
        if not stat.S_ISREG(before.st_mode) or (not system and before.st_nlink != 1) or before.st_nlink < 1 or before.st_size <= 0:
            deny("unsafe-descriptor: " + str(path))
        if before.st_mode & 0o022:
            deny("writable-descriptor: " + str(path))
        if system and (before.st_uid != 0 or before.st_gid != 0):
            deny("unowned-system-descriptor: " + str(path))
        data = read_fd(fd, maximum, single_link=not system)
        after = os.fstat(fd)
        if identity(before) != identity(after):
            deny("drift-descriptor: " + str(path))
        return {"path": str(path), "dev": before.st_dev, "inode": before.st_ino,
                "uid": before.st_uid, "gid": before.st_gid, "mode": stat.S_IMODE(before.st_mode),
                "nlink": before.st_nlink, "size": before.st_size, "sha256": sha256(data)}
    finally:
        os.close(fd)


def checked_directory(path: Path) -> dict[str, int]:
    if path.is_symlink():
        deny("symlinked-directory: " + str(path))
    fd = os.open(path, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC)
    try:
        info = os.fstat(fd)
        if not stat.S_ISDIR(info.st_mode) or info.st_nlink < 2 or info.st_mode & 0o022:
            deny("unsafe-directory: " + str(path))
        return {"dev": info.st_dev, "inode": info.st_ino, "uid": info.st_uid, "gid": info.st_gid,
                "mode": stat.S_IMODE(info.st_mode), "nlink": info.st_nlink}
    finally:
        os.close(fd)


def checked_system_directory_selector(path: Path) -> dict[str, object]:
    parent = path.parent
    parent_before = checked_directory(parent)
    if parent_before["uid"] != 0 or parent_before["gid"] != 0:
        deny("unowned-system-directory: " + str(parent))

    selector_before = os.lstat(path)
    if not stat.S_ISLNK(selector_before.st_mode):
        deny("non-symlinked-system-selector: " + str(path))
    if selector_before.st_uid != 0 or selector_before.st_gid != 0 or selector_before.st_nlink != 1:
        deny("unsafe-system-selector: " + str(path))
    target_name = os.readlink(path)
    target_component = Path(target_name)
    if (not target_name or target_component.is_absolute() or len(target_component.parts) != 1
            or target_name in {".", ".."}):
        deny("unsafe-system-selector-target: " + str(path))

    target_path = parent / target_name
    target = checked_directory(target_path)
    if target["uid"] != 0 or target["gid"] != 0:
        deny("unowned-system-directory: " + str(target_path))
    selector_after = os.lstat(path)
    parent_after = checked_directory(parent)
    if identity(selector_before) != identity(selector_after) or os.readlink(path) != target_name:
        deny("drift-system-selector: " + str(path))
    if parent_before != parent_after:
        deny("drift-system-directory: " + str(parent))
    return {
        "selector": {"path": str(path), "dev": selector_before.st_dev, "inode": selector_before.st_ino,
                     "uid": selector_before.st_uid, "gid": selector_before.st_gid,
                     "mode": stat.S_IMODE(selector_before.st_mode), "nlink": selector_before.st_nlink,
                     "size": selector_before.st_size, "target": target_name, "type": "symlink"},
        "parent": {"path": str(parent), **parent_before},
        "target": {"path": str(target_path), **target},
    }


def checked_authority_root(path: Path, expected_files: frozenset[str]) -> dict[str, int]:
    fd = os.open(path, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC)
    try:
        info = os.fstat(fd)
        if (not stat.S_ISDIR(info.st_mode) or info.st_nlink < 2 or info.st_uid != os.getuid()
                or info.st_gid != os.getgid() or stat.S_IMODE(info.st_mode) != 0o700):
            deny("unsafe-authority-root")
        if set(os.listdir(fd)) != set(expected_files):
            deny("authority-inventory-mismatch")
        return {"dev": info.st_dev, "inode": info.st_ino, "uid": info.st_uid, "gid": info.st_gid,
                "mode": stat.S_IMODE(info.st_mode)}
    finally:
        os.close(fd)


def git(source: Path, *args: str) -> str:
    result = subprocess.run(["/usr/bin/git", "-C", str(source), *args], stdin=subprocess.DEVNULL,
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
                            env={"PATH": "/usr/bin:/bin:/usr/sbin:/sbin", "LC_ALL": "C"}, check=False)
    if result.returncode != 0:
        deny("git-verification-failed: " + args[0])
    return result.stdout


def under(child: Path, parent: Path) -> bool:
    try:
        child.resolve().relative_to(parent.resolve())
        return True
    except ValueError:
        return False


def tree_digest(fd: int, prefix: str) -> str:
    digest = hashlib.sha256()
    before = identity(os.fstat(fd))
    for child in sorted(os.listdir(fd)):
        if child.startswith(".") or NAME.fullmatch(child) is None:
            deny("unsafe-manifest-tree-name")
        cfd = os.open(child, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC, dir_fd=fd)
        try:
            meta = os.fstat(cfd)
            path = prefix + "/" + child
            if stat.S_ISDIR(meta.st_mode):
                digest.update(bytes.fromhex(tree_digest(cfd, path)))
            elif stat.S_ISREG(meta.st_mode) and meta.st_nlink == 1 and not meta.st_mode & 0o022:
                payload = read_fd(cfd, 256 * 1024 * 1024)
                digest.update((path + "|" + str(meta.st_size) + "|" + sha256(payload) + "\n").encode("utf-8"))
            else:
                deny("unsafe-manifest-tree-node")
        finally:
            os.close(cfd)
    if identity(os.fstat(fd)) != before:
        deny("drift-manifest-tree")
    # The source manifest's tree scheme is the hash of its complete textual
    # member record stream, not a recursive composition of child digests.
    # Recompute that stream directly so this function cannot silently accept
    # a different tree representation.
    stream = hashlib.sha256()
    def visit(directory_fd: int, name: str) -> None:
        start = identity(os.fstat(directory_fd))
        for leaf in sorted(os.listdir(directory_fd)):
            if leaf.startswith(".") or NAME.fullmatch(leaf) is None:
                deny("unsafe-manifest-tree-name")
            leaf_fd = os.open(leaf, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC, dir_fd=directory_fd)
            try:
                leaf_meta = os.fstat(leaf_fd)
                leaf_path = name + "/" + leaf
                if stat.S_ISDIR(leaf_meta.st_mode):
                    visit(leaf_fd, leaf_path)
                elif stat.S_ISREG(leaf_meta.st_mode) and leaf_meta.st_nlink == 1 and not leaf_meta.st_mode & 0o022:
                    payload = read_fd(leaf_fd, 256 * 1024 * 1024)
                    stream.update((leaf_path + "|" + str(leaf_meta.st_size) + "|" + sha256(payload) + "\n").encode("utf-8"))
                else:
                    deny("unsafe-manifest-tree-node")
            finally:
                os.close(leaf_fd)
        if identity(os.fstat(directory_fd)) != start:
            deny("drift-manifest-tree")
    visit(fd, prefix)
    return stream.hexdigest()


def verify_manifest(source: Path) -> tuple[dict[str, object], str]:
    manifest_path = source / "script/source_snapshot_manifest.jsonl"
    raw = descriptor(manifest_path, maximum=1024 * 1024)
    fd = os.open(manifest_path, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC)
    root_fd = os.open(source, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC)
    try:
        payload = read_fd(fd, 1024 * 1024)
        lines = payload.decode("utf-8", "strict").splitlines()
        rows = [json.loads(line) for line in lines]
        if not rows or any(canonical(row).rstrip(b"\n").decode("utf-8") != line for row, line in zip(rows, lines)):
            deny("noncanonical-source-manifest")
        paths = [row.get("path") for row in rows]
        if paths != sorted(paths) or len(paths) != len(set(paths)):
            deny("unsafe-source-manifest-inventory")
        for row in rows:
            if set(row) - {"schema", "type", "path", "mode", "size", "sha256"} or row.get("schema") != "lidswitch-source-manifest-v1":
                deny("unsafe-source-manifest-row")
            relative = row.get("path")
            if not isinstance(relative, str) or relative.startswith("/") or ".." in relative.split("/"):
                deny("unsafe-source-manifest-path")
            entry_fd = os.open(relative, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC, dir_fd=root_fd)
            try:
                info = os.fstat(entry_fd)
                if row.get("type") == "file":
                    payload_entry = read_fd(entry_fd, 256 * 1024 * 1024)
                    if (not stat.S_ISREG(info.st_mode) or info.st_size != row.get("size") or
                            stat.S_IMODE(info.st_mode) != row.get("mode") or sha256(payload_entry) != row.get("sha256")):
                        deny("source-manifest-file-mismatch: " + relative)
                elif row.get("type") == "tree":
                    if not stat.S_ISDIR(info.st_mode) or tree_digest(entry_fd, relative) != row.get("sha256"):
                        deny("source-manifest-tree-mismatch: " + relative)
                else:
                    deny("unsafe-source-manifest-row")
            finally:
                os.close(entry_fd)
        return raw, sha256(payload)
    finally:
        os.close(root_fd)
        os.close(fd)


ENTRY = r'''#!/usr/bin/python3
import argparse, errno, fcntl, hashlib, json, os, re, stat, sys, tempfile
EX=74; ROLES={"wrapper":30,"common":31,"envelope":32,"profile":33,"safe_file":34,"supervisor":35,"source_manifest":36,"capture_package":42,"assemble_package":43,"candidate_core":44,"build_manifest":45,"package_manifest":46,"validate_candidate":47,"validate_dmg":48,"release_identity":49,"icon":50}
POST_CHILD_STAGES=("internal","bash-reassert","role-reassert-wrapper","role-reassert-common","role-reassert-envelope","role-reassert-profile","role-reassert-safe_file","role-reassert-supervisor","role-reassert-source_manifest","role-reassert-capture_package","role-reassert-assemble_package","role-reassert-candidate_core","role-reassert-build_manifest","role-reassert-package_manifest","role-reassert-validate_candidate","role-reassert-validate_dmg","role-reassert-release_identity","role-reassert-icon","child-status-classify","receipt-open","receipt-read","receipt-parse","receipt-success-validate","release-receipt-open-read","release-receipt-parse-validate","pre-snapshot-select","pre-snapshot-tuple","post-snapshot-select","post-snapshot-tuple","pre-assertion-parse","post-assertion-parse","save-live-state-retained-receipt","save-preflight-state-snapshot","save-postflight-state-snapshot","save-preflight-pmset-assertions","save-postflight-pmset-assertions","live-envelope-write")
ROLE_REASSERT_STAGES={"wrapper":"role-reassert-wrapper","common":"role-reassert-common","envelope":"role-reassert-envelope","profile":"role-reassert-profile","safe_file":"role-reassert-safe_file","supervisor":"role-reassert-supervisor","source_manifest":"role-reassert-source_manifest","capture_package":"role-reassert-capture_package","assemble_package":"role-reassert-assemble_package","candidate_core":"role-reassert-candidate_core","build_manifest":"role-reassert-build_manifest","package_manifest":"role-reassert-package_manifest","validate_candidate":"role-reassert-validate_candidate","validate_dmg":"role-reassert-validate_dmg","release_identity":"role-reassert-release_identity","icon":"role-reassert-icon"}
def die(): raise SystemExit(EX)
def ident(s): return (s.st_dev,s.st_ino,s.st_uid,s.st_gid,stat.S_IMODE(s.st_mode),s.st_nlink,s.st_size)
def read(fd,limit=8*1024*1024):
 try:
  before=os.fstat(fd)
  if not stat.S_ISREG(before.st_mode) or before.st_nlink!=1 or not 0<before.st_size<=limit: die()
  os.lseek(fd,0,os.SEEK_SET); out=bytearray()
  while len(out)<before.st_size:
   try: p=os.read(fd,min(131072,before.st_size-len(out)))
   except InterruptedError: continue
   if not p: die()
   out.extend(p)
  if os.read(fd,1) or ident(os.fstat(fd))!=ident(before): die()
  return bytes(out)
 except OSError: die()
def dup(fd):
 try: return fcntl.fcntl(fd,fcntl.F_DUPFD_CLOEXEC,64)
 except OSError: die()
def close(fd):
 try: os.close(fd)
 except OSError: die()
def child_rc_class(status):
 if os.WIFEXITED(status): return "zero" if os.WEXITSTATUS(status)==0 else "nonzero"
 if os.WIFSIGNALED(status): return "signaled"
 return "unknown"
def retained_receipt_presence(control_fd):
 try:
  meta=os.stat("live-state-retained.receipt",dir_fd=control_fd,follow_symlinks=False)
 except OSError as error:
  return "absent" if error.errno==errno.ENOENT else "unknown"
 return "present" if stat.S_ISREG(meta.st_mode) and meta.st_nlink==1 else "unknown"
def hosted_entry_failure_block(stage,status,control_fd):
 if stage not in POST_CHILD_STAGES: stage="internal"
 block=("LIDSWITCH_HOSTED_ENTRY_FAILURE\nschema=1\nstage="+stage+"\nchild_rc_class="+child_rc_class(status)+"\nreceipt_presence="+retained_receipt_presence(control_fd)+"\n").encode("ascii")
 if len(block)>256: die()
 return block
def emit_hosted_entry_failure(emitted,stage,status,control_fd):
 if emitted[0]: return False
 emitted[0]=True
 try: os.write(2,hosted_entry_failure_block(stage,status,control_fd))
 except BaseException: pass
 return True
def success_snapshot_scalars_valid(vals):
 try:
  return vals.get("kernel_build")=="25E246" and re.fullmatch(r"[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}",vals["kernel_boot"]) is not None and re.fullmatch(r"[0-9]+(?:[.][0-9]+)?",vals["kernel_monotonic"]) is not None and re.fullmatch(r"[0-9]{9,12}",vals["captured_epoch"]) is not None
 except (KeyError,TypeError): return False
def role(root,rel,want,dirs):
 if not isinstance(rel,str) or rel.startswith("/") or ".." in rel.split("/"): die()
 parent=root; opened=[]
 try:
  parts=rel.split("/")
  for part in parts[:-1]:
   parent=os.open(part,os.O_RDONLY|os.O_DIRECTORY|os.O_NOFOLLOW|os.O_CLOEXEC,dir_fd=parent); opened.append(parent)
   meta=os.fstat(parent); expected=dirs.get(part)
   if not isinstance(expected,dict) or ident(meta)[:-1] != tuple(expected.get(k) for k in ("dev","inode","uid","gid","mode","nlink")): die()
  fd=os.open(parts[-1],os.O_RDONLY|os.O_NOFOLLOW|os.O_CLOEXEC,dir_fd=parent)
  raw=read(fd); meta=os.fstat(fd)
  if ident(meta)+(hashlib.sha256(raw).hexdigest(),)!=tuple(want.get(k) for k in ("dev","inode","uid","gid","mode","nlink","size","sha256")): die()
  os.lseek(fd,0,os.SEEK_SET); return fd
 except OSError: die()
 finally:
  for item in opened:
   try: os.close(item)
   except OSError: die()
def private(prefix):
 try:
  p=tempfile.mkdtemp(prefix=prefix,dir="/private/tmp"); fd=os.open(p,os.O_RDONLY|os.O_DIRECTORY|os.O_NOFOLLOW|os.O_CLOEXEC); s=os.fstat(fd)
  if not stat.S_ISDIR(s.st_mode) or s.st_uid!=os.getuid() or stat.S_IMODE(s.st_mode)!=0o700 or s.st_nlink<2: die()
  os.fchown(fd,-1,os.getgid()); return p,dup(fd)
 except OSError: die()
 finally:
  try: os.close(fd)
  except BaseException: pass
def bash(spec):
 try:
  fd=os.open("/bin/bash",os.O_RDONLY|os.O_NOFOLLOW|os.O_CLOEXEC); raw=read(fd,16*1024*1024); s=os.fstat(fd); os.close(fd)
  if ident(s)+(hashlib.sha256(raw).hexdigest(),)!=tuple(spec.get(k) for k in ("dev","inode","uid","gid","mode","nlink","size","sha256")): die()
 except OSError: die()
def power_diagnostic(root,present):
 def load(name):
  if name not in present: return "missing",None
  fd=None
  try:
   fd=os.open(name,os.O_RDONLY|os.O_NOFOLLOW|os.O_CLOEXEC,dir_fd=root); before=os.fstat(fd)
   if not stat.S_ISREG(before.st_mode) or before.st_nlink!=1 or before.st_size<0 or before.st_size>65536: return "unreadable",None
   data=bytearray()
   while len(data)<before.st_size:
    chunk=os.read(fd,min(131072,before.st_size-len(data)))
    if not chunk: return "unreadable",None
    data.extend(chunk)
   if os.read(fd,1) or ident(os.fstat(fd))!=ident(before): return "unreadable",None
   return "ok",bytes(data).decode("utf-8","strict")
  except (OSError,UnicodeError): return "unreadable",None
  finally:
   if fd is not None:
    try: os.close(fd)
    except OSError: pass
 result={}
 state,batt=load("pre-initial.pmset-batt")
 if state!="ok": result["drawing"]=state
 else:
  matches=[]
  for line in batt.splitlines():
   if line.strip()=="Now drawing from 'AC Power'": matches.append("ac")
   elif line.strip()=="Now drawing from 'Battery Power'": matches.append("battery")
  result["drawing"]=matches[0] if len(matches)==1 else "unparsed"
 state,live=load("pre-initial.pmset-live")
 if state!="ok": result["live_sleep_disabled"]=state
 else:
  matches=[parts[1] for line in live.splitlines() if len(parts:=line.split())==2 and parts[0]=="SleepDisabled" and parts[1] in ("0","1")]
  result["live_sleep_disabled"]=matches[0] if len(matches)==1 else "unparsed"
 state,custom=load("pre-initial.pmset-custom")
 if state!="ok": result["custom_ac_sleep"]=state
 else:
  in_ac=False; matches=[]
  for line in custom.splitlines():
   if line=="AC Power:": in_ac=True; continue
   if line and not line[0].isspace(): in_ac=False
   parts=line.split()
   if in_ac and len(parts)==2 and parts[0]=="sleep" and 1<=len(parts[1])<=4 and all("0"<=ch<="9" for ch in parts[1]): matches.append(parts[1])
  result["custom_ac_sleep"]=matches[0] if len(matches)==1 else "unparsed"
 return result
def main():
 p=argparse.ArgumentParser(allow_abbrev=False); p.add_argument("--repo",required=True); p.add_argument("--contract-fd",required=True,type=int); p.add_argument("--contract-sha256",required=True); p.add_argument("--contract-size",required=True,type=int); p.add_argument("--hosted-receipt",required=True); p.add_argument("--release-candidate",action="store_true"); p.add_argument("wrapper",choices=("build",)); p.add_argument("args",nargs=argparse.REMAINDER); a=p.parse_args()
 if not a.release_candidate or len(a.contract_sha256)!=64 or a.contract_size<=0: die()
 raw=read(a.contract_fd)
 if len(raw)!=a.contract_size or hashlib.sha256(raw).hexdigest()!=a.contract_sha256: die()
 try: c=json.loads(raw.decode("utf-8"))
 except BaseException: die()
 if json.dumps(c,sort_keys=True,separators=(",",":")).encode()+b"\n"!=raw or c.get("schema")!="lidswitch-hosted-held-contract-v1" or c.get("fd_map")!={**ROLES,"repo_root":37,"control_root":38,"execution_root":39,"terminal_pipe":40,"startup_gate":41}: die()
 if set(c.get("roles",{}))!=set(ROLES) or c.get("roles",{}).get("wrapper",{}).get("path")!="script/run_swift_build_safely.sh": die()
 close(a.contract_fd); root=os.open(a.repo,os.O_RDONLY|os.O_DIRECTORY|os.O_NOFOLLOW|os.O_CLOEXEC); rs=os.fstat(root)
 if not stat.S_ISDIR(rs.st_mode) or rs.st_mode&0o022: die()
 fds={n:dup(role(root,c["roles"][n]["path"],c["roles"][n],c.get("directories",{}))) for n in ROLES}; control,cfd=private("lidswitch-envelope."); execution,xfd=private("lidswitch-swift.")
 gr,gw=os.pipe(); tr,tw=os.pipe(); bash(c["bash"])
 child={30:fds["wrapper"],31:fds["common"],32:fds["envelope"],33:fds["profile"],34:fds["safe_file"],35:fds["supervisor"],36:fds["source_manifest"],37:root,38:cfd,39:xfd,40:tw,41:gr}
 for fd in child.values(): os.lseek(fd,0,os.SEEK_SET) if fd in fds.values() else None
 acts=[(os.POSIX_SPAWN_OPEN,0,"/dev/null",os.O_RDONLY,0)]+[(os.POSIX_SPAWN_DUP2,v,k) for k,v in child.items()]+[(os.POSIX_SPAWN_CLOSE,v) for v in set(child.values())]
 env={"PATH":"/usr/bin:/bin:/usr/sbin:/sbin","LC_ALL":"C","LIDSWITCH_HELD_ENTRY":"v1","LIDSWITCH_HELD_FD_MAP":"30,31,32,33,34,35,36,37,38,39,40,41","LIDSWITCH_HELD_REPO_ROOT":a.repo,"LIDSWITCH_HELD_CONTROL_ROOT":control,"LIDSWITCH_HELD_EXECUTION_ROOT":execution,"LIDSWITCH_HELD_RELEASE_CANDIDATE":"v1","LIDSWITCH_HELD_HOSTED_RUNNER_AUTHORITY":"v1"}
 pid=os.posix_spawn("/bin/bash",["/bin/bash","-p","--","/dev/fd/30",*a.args],env,file_actions=acts); close(gr); os.write(gw,b"R"); close(gw); close(tw); _,status=os.waitpid(pid,0)
 stage="internal"; original_die=die; emitted=[False]
 def guarded_die():
  emit_hosted_entry_failure(emitted,stage,status,cfd)
  original_die()
 globals()["die"]=guarded_die
 stage="bash-reassert"; bash(c["bash"])
 for n in ROLES:
  stage=ROLE_REASSERT_STAGES[n]
  q=role(root,c["roles"][n]["path"],c["roles"][n],c.get("directories",{})); close(q)
 stage="child-status-classify"
 rc=os.WEXITSTATUS(status) if os.WIFEXITED(status) else EX
 stage="receipt-open"
 try: receipt_fd=os.open("live-state-retained.receipt",os.O_RDONLY|os.O_NOFOLLOW|os.O_CLOEXEC,dir_fd=cfd)
 except OSError:
  allowed=("pre-initial.pmset-batt","pre-initial.pmset-live","pre-initial.pmset-custom","pre-initial.pmset-assertions","pre-initial.launchctl-print","live-preflight-initial.kv","live-preflight.kv","live-postflight.kv","live-state-retained.receipt")
  try: present=tuple(name for name in allowed if name in os.listdir(cfd))
  except OSError: die()
  values={}
  for name in ("live-preflight.kv","live-preflight-initial.kv"):
   if name not in present: continue
   try: diagnostic=read(os.open(name,os.O_RDONLY|os.O_NOFOLLOW|os.O_CLOEXEC,dir_fd=cfd),65536)
   except SystemExit: continue
   try:
    for line in diagnostic.decode("utf-8","strict").splitlines():
     key,value=line.split("=",1)
     if key in ("host_class","kernel_build","power_source","sleep_disabled","launchd_presence","status_presence","authority_kind","status_reason_class") and 0<len(value)<=128 and all(ch.isalnum() or ch in "-._" for ch in value): values[key]=value
   except BaseException: die()
   break
  power=power_diagnostic(cfd,present)
  fields=("host_class","kernel_build","power_source","sleep_disabled","launchd_presence","status_presence","authority_kind","status_reason_class")
  os.write(2,("LIDSWITCH_HOSTED_PREFLIGHT_FAILURE\nschema=2\ncontrol_files="+(",".join(present) if present else "none")+"\n"+"".join(key+"="+power[key]+"\n" for key in ("drawing","live_sleep_disabled","custom_ac_sleep"))+"".join(key+"="+values.get(key,"missing")+"\n" for key in fields)).encode()); die()
 stage="receipt-read"; receipt=read(receipt_fd,65536)
 stage="receipt-parse"
 try:
  rows={};
  for line in receipt.decode("utf-8","strict").splitlines():
   k,v=line.split("=",1)
   if not k or k in rows: die()
   rows[k]=v
  expected_keys={"schema","nonce","outcome","child_command_exit","wrapper_exit","preflight_sha256","postflight_sha256","host_preserved","benchmark_published","error","capture_identifiers","control_root","execution_root"}
  stage="receipt-success-validate"
  if rc!=0:
   outcome=rows.get("outcome",""); error=rows.get("error",""); child_exit=rows.get("child_command_exit",""); wrapper_exit=rows.get("wrapper_exit","")
   safe=lambda value: 0<len(value)<=128 and all(ch.isalnum() or ch in "-._" for ch in value)
   if set(rows)!=expected_keys or rows.get("schema")!="3" or not safe(outcome) or not safe(error) or not child_exit.isdigit() or not wrapper_exit.isdigit() or int(child_exit)>256 or int(wrapper_exit)>255: die()
   os.write(2,("LIDSWITCH_HOSTED_WRAPPER_FAILURE\nschema=1\noutcome="+outcome+"\nchild_command_exit="+child_exit+"\nwrapper_exit="+wrapper_exit+"\nerror="+error+"\n").encode()); die()
  capture_names=("app-bin-path","app-build","helper-bin-path","helper-build","helper-identity","helper-sign","helper-verify")
  capture_values=rows.get("capture_identifiers","").split(",")
  if set(rows)!=expected_keys or rows.get("schema")!="3" or not rows.get("nonce") or rows.get("child_command_exit")!="0" or rows.get("wrapper_exit")!="0" or rows.get("outcome")!="preserved" or rows.get("host_preserved")!="true" or rows.get("benchmark_published") not in ("true","false") or rows.get("error")!="none" or rows.get("control_root")!=control or rows.get("execution_root")!=execution or any(len(rows.get(name,""))!=64 or any(ch not in "0123456789abcdef" for ch in rows[name]) for name in ("preflight_sha256","postflight_sha256")) or len(capture_values)!=len(capture_names) or any(not value.startswith(name+":") or len(value)!=len(name)+130 or any(ch not in "0123456789abcdef:" for ch in value[len(name)+1:]) or value[len(name)+65]!=":" for name,value in zip(capture_names,capture_values)) or rc!=0: die()
  stage="release-receipt-open-read"
  release_raw=read(os.open(os.path.join(execution,"release-output","build-receipt.json"),os.O_RDONLY|os.O_NOFOLLOW|os.O_CLOEXEC),262144)
  stage="release-receipt-parse-validate"
  release=json.loads(release_raw.decode("utf-8"))
  if json.dumps(release,sort_keys=True,separators=(",",":")).encode()+b"\n"!=release_raw or tuple(release.get("captures",{}))!=capture_names or any(capture_values[index]!=name+":"+release["captures"][name] for index,name in enumerate(capture_names)): die()
  def snap(names,want,phases,select_stage,tuple_stage):
   nonlocal stage
   for name in names:
    stage=select_stage
    try: raw=read(os.open(name,os.O_RDONLY|os.O_NOFOLLOW|os.O_CLOEXEC,dir_fd=cfd),65536)
    except OSError: continue
    if hashlib.sha256(raw).hexdigest()!=want: continue
    stage=tuple_stage
    vals={}
    for line in raw.decode("utf-8","strict").splitlines():
     k,v=line.split("=",1)
     if not k or k in vals: die()
     vals[k]=v
    required={"schema":"1","nonce":rows.get("nonce"),"phase":phases[name],"host_class":"idle-uninstalled","power_source":"ac","sleep_disabled":"absent","sleep_proof":"pmset-assertions-system-prevent-system-sleep-0","ac_sleep_minutes":"0","status_presence":"absent","status_state":"none","status_reason":"none","status_reason_class":"none","status_session":"none","status_updated":"none","status_monotonic":"none","status_boot_id":"none","status_schema":"absent","status_evidence":"none","status_meta":"absent","launchd_presence":"absent","launchd_state":"none","launchd_pid":"none","launchd_program":"none","plist_contract":"absent","plist_qualified_build":"absent","plist_meta":"absent","plist_sha256":"absent","helper_path":"absent","helper_meta":"absent","app_meta":"absent","root_support_structure":"absent","private_applied_meta":"absent","private_terminal_meta":"absent","private_reservations_meta":"absent","private_proof_meta":"absent","private_lock_meta":"absent","original_ac_meta":"absent","original_battery_meta":"absent","authority_kind":"none","lease_session":"none","lease_boot":"none","lease_expires":"none","lease_issued_mono":"none","lease_expires_mono":"none","lease_uid":"none","lease_build":"none","lease_meta":"absent","lease_lifetime":"none","user_history_diagnostic_meta":"absent"}
    if any(vals.get(k)!=v for k,v in required.items()) or set(vals)!=set(required)|{"kernel_boot","kernel_build","kernel_monotonic","captured_epoch"} or not success_snapshot_scalars_valid(vals): die()
    return raw,name
   die()
  def assertions(name,assertion_stage):
   nonlocal stage
   stage=assertion_stage
   raw=read(os.open(name,os.O_RDONLY|os.O_NOFOLLOW|os.O_CLOEXEC,dir_fd=cfd),65536)
   try:
    lines=raw.decode("utf-8","strict").splitlines(); header=lines.index("Assertion status system-wide:"); listed=lines.index("Listed by owning process:")
    if header>4 or listed<=header or lines.count("Assertion status system-wide:")!=1 or lines.count("Listed by owning process:")!=1 or any(not line or len(line)>256 or any(ord(ch)<32 or ord(ch)>126 for ch in line) for line in lines[:header]): die()
    matches=[line for line in lines[header+1:listed] if line.strip().startswith("PreventSystemSleep")]; all_matches=[line for line in lines if line.strip().startswith("PreventSystemSleep")]
    if len(all_matches)!=1 or matches!=all_matches or re.fullmatch(r"[ \\t]+PreventSystemSleep[ \\t]+0",matches[0]) is None: die()
   except BaseException: die()
   return raw
  pre,pre_name=snap(("live-preflight.kv","live-preflight-initial.kv"),rows.get("preflight_sha256",""),{"live-preflight.kv":"pre","live-preflight-initial.kv":"pre-initial"},"pre-snapshot-select","pre-snapshot-tuple")
  post,post_name=snap(("live-postflight.kv",),rows.get("postflight_sha256",""),{"live-postflight.kv":"post"},"post-snapshot-select","post-snapshot-tuple")
  pre_assertions=assertions("pre.pmset-assertions" if pre_name=="live-preflight.kv" else "pre-initial.pmset-assertions","pre-assertion-parse")
  post_assertions=assertions("post.pmset-assertions","post-assertion-parse")
  destination=os.path.dirname(a.hosted_receipt)
  def save(name,data):
   fd=os.open(os.path.join(destination,name),os.O_WRONLY|os.O_CREAT|os.O_EXCL|os.O_NOFOLLOW|os.O_CLOEXEC,0o400)
   try: os.write(fd,data); os.fsync(fd)
   finally: os.close(fd)
  stage="save-live-state-retained-receipt"; save("live-state-retained.receipt",receipt)
  stage="save-preflight-state-snapshot"; save("preflight-state.snapshot",pre)
  stage="save-postflight-state-snapshot"; save("postflight-state.snapshot",post)
  stage="save-preflight-pmset-assertions"; save("preflight.pmset-assertions",pre_assertions)
  stage="save-postflight-pmset-assertions"; save("postflight.pmset-assertions",post_assertions)
 except BaseException: die()
 stage="live-envelope-write"
 try:
  with open(a.hosted_receipt,"xb") as out: out.write(json.dumps({"schema":"lidswitch-hosted-live-envelope-v3","receipt_sha256":hashlib.sha256(receipt).hexdigest(),"preflight":{"snapshot_sha256":hashlib.sha256(pre).hexdigest(),"assertions_sha256":hashlib.sha256(pre_assertions).hexdigest(),"sleep_proof":"pmset-assertions-system-prevent-system-sleep-0","phase":"pre" if pre_name=="live-preflight.kv" else "pre-initial"},"postflight":{"snapshot_sha256":hashlib.sha256(post).hexdigest(),"assertions_sha256":hashlib.sha256(post_assertions).hexdigest(),"sleep_proof":"pmset-assertions-system-prevent-system-sleep-0","phase":"post"},"wrapper_exit":rc},sort_keys=True,separators=(",",":")).encode()+b"\n")
 except OSError: die()
 os.write(2,("LIDSWITCH_HOSTED_HELD_RECEIPT\nschema=1\nreceipt_sha256="+hashlib.sha256(receipt).hexdigest()+"\nwrapper_exit="+str(rc)+"\n").encode()); raise SystemExit(rc)
if __name__=="__main__":
 try: main()
 except SystemExit: raise
 except BaseException: die()
'''


def policy(path: Path) -> dict[str, object]:
    raw = descriptor(path, maximum=1024 * 1024)
    value = json.loads(Path(path).read_text("utf-8"))
    if canonical(value) != Path(path).read_bytes() or set(value) != {"runner", "schema", "source", "source_manifest_sha256", "toolchain"} or value.get("schema") != "lidswitch-hosted-runner-policy-v2":
        deny("invalid-hosted-policy")
    runner = value.get("runner")
    toolchain = value.get("toolchain")
    if runner != {"architecture": "arm64", "image_versions": REVIEWED_IMAGES, "kernel": "25E246", "label": "macos-26"}:
        deny("policy-runner-binding-mismatch")
    if toolchain != {"developer_dir": "/Library/Developer/CommandLineTools", "sdk_name": "macosx", "swift_driver": "/Library/Developer/CommandLineTools/usr/bin/swift"}:
        deny("policy-toolchain-binding-mismatch")
    source = value.get("source")
    if source != {"commit": SOURCE_COMMIT, "tree": SOURCE_TREE, "wrapper_sha256": WRAPPER_SHA256}:
        deny("policy-source-binding-mismatch")
    return {"descriptor": raw, "value": value}


def prepare(source: Path, authority: Path, policy_path: Path) -> dict[str, object]:
    try:
        pol = policy(policy_path)
    except Denied as error:
        deny("prepare-policy:" + str(error))
    source = source.resolve(strict=True)
    authority = authority.resolve(strict=False)
    if under(authority, source):
        deny("authority-must-remain-outside-source")
    if authority.exists() or authority.is_symlink():
        deny("authority-must-not-exist")
    root = checked_directory(source)
    if git(source, "rev-parse", "HEAD").strip() != SOURCE_COMMIT or git(source, "rev-parse", "HEAD^{tree}").strip() != SOURCE_TREE:
        deny("source-commit-or-tree-mismatch")
    if git(source, "status", "--porcelain=v1", "--untracked-files=all"):
        deny("source-checkout-not-clean")
    try:
        manifest, manifest_sha = verify_manifest(source)
    except Denied as error:
        deny("prepare-source-manifest:" + str(error))
    if manifest_sha != pol["value"]["source_manifest_sha256"]:
        deny("source-manifest-digest-mismatch")
    roles: dict[str, dict[str, object]] = {}
    directories: dict[str, dict[str, int]] = {}
    for name, (_fd, relative) in ROLES.items():
        try:
            roles[name] = descriptor(source / relative, maximum=256 * 1024 * 1024)
        except Denied as error:
            deny("prepare-role-" + name + ":" + str(error))
        roles[name]["path"] = relative
        for component in relative.split("/")[:-1]:
            directories.setdefault(component, checked_directory(source / component))
    if roles["wrapper"]["sha256"] != WRAPPER_SHA256:
        deny("unchanged-wrapper-digest-mismatch")
    try:
        bash = descriptor(Path("/bin/bash"), system=True, maximum=16 * 1024 * 1024)
        python = descriptor(Path("/usr/bin/python3"), system=True, maximum=64 * 1024 * 1024)
        swift = descriptor(Path("/Library/Developer/CommandLineTools/usr/bin/swift-frontend"), system=True, maximum=512 * 1024 * 1024)
        sdk = checked_system_directory_selector(Path("/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"))
    except Denied as error:
        deny("prepare-system-toolchain:" + str(error))
    authority.mkdir(mode=0o700, parents=False)
    if stat.S_IMODE(os.stat(authority, follow_symlinks=False).st_mode) != 0o700:
        deny("unsafe-authority-root")
    contract = {"schema": "lidswitch-hosted-held-contract-v1", "fd_map": FD_MAP, "roles": roles,
                "directories": directories, "bash": bash, "source_manifest": manifest["sha256"]}
    contract_bytes = canonical(contract)
    entry = authority / "hosted-held-entry.py"
    contract_path = authority / "hosted-held-contract.json"
    ledger_path = authority / "hosted-authority-ledger.json"
    for path, data, mode in ((entry, ENTRY.encode("utf-8"), 0o500), (contract_path, contract_bytes, 0o400)):
        fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW | os.O_CLOEXEC, mode)
        try:
            os.write(fd, data); os.fsync(fd)
        finally:
            os.close(fd)
    # Create every authority leaf before freezing the directory descriptor.
    # Some filesystems update directory link metadata when a child is added;
    # writing an already-created ledger leaf does not change that identity.
    ledger_fd = os.open(ledger_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW | os.O_CLOEXEC, 0o400)
    try:
        info = checked_authority_root(authority, AUTHORITY_INITIAL_FILES)
        ledger = {"schema": "lidswitch-hosted-authority-ledger-v1", "policy": pol["descriptor"],
                  "source": {"commit": SOURCE_COMMIT, "tree": SOURCE_TREE, "root": root,
                             "manifest_sha256": manifest_sha, "manifest_descriptor": manifest},
                  "system": {"python": python, "bash": bash, "swift_frontend": swift, "sdk_root": sdk,
                             "developer_dir": "/Library/Developer/CommandLineTools"}, "wrapper_sha256": WRAPPER_SHA256,
                  "generated": {"entry": descriptor(entry), "contract": descriptor(contract_path), "root": info}}
        data = canonical(ledger); os.write(ledger_fd, data); os.fsync(ledger_fd)
    finally:
        os.close(ledger_fd)
    # This receipt is deliberately emitted outside the generated ledger: the
    # next workflow step must carry these values as explicit build inputs.
    return {"schema": "lidswitch-hosted-prepare-v2", "authority": str(authority),
            "ledger": descriptor(ledger_path), "entry": descriptor(entry),
            "contract": descriptor(contract_path), "source_manifest_sha256": manifest_sha}


def _expected(descriptor_value: dict[str, object], name: str, sha: str, size: int) -> None:
    if not re.fullmatch(r"[0-9a-f]{64}", sha) or size <= 0 or descriptor_value.get("sha256") != sha or descriptor_value.get("size") != size:
        deny("external-expected-" + name + "-mismatch")


def build(source: Path, authority: Path, policy_path: Path, expected: dict[str, tuple[str, int]]) -> dict[str, object]:
    prepared = prepare_recheck(source, authority, policy_path, completed=False)
    ledger = prepared["ledger"]
    generated = ledger["generated"]
    entry = authority / "hosted-held-entry.py"
    contract = authority / "hosted-held-contract.json"
    for name, path in (("entry", entry), ("contract", contract)):
        observed = descriptor(path)
        if observed != generated[name]:
            deny("generated-authority-drift: " + name)
    _expected(descriptor(ledger_path := authority / "hosted-authority-ledger.json"), "ledger", *expected["ledger"])
    _expected(descriptor(entry), "entry", *expected["entry"])
    _expected(descriptor(contract), "contract", *expected["contract"])
    contract_fd = os.open(contract, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC)
    entry_fd = os.open(entry, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC)
    try:
        # /dev/fd is backed by the descriptor just verified above; a mutable
        # authority pathname is not an execution authority.
        # CPython opens script pathnames more than once.  On macOS, /dev/fd
        # duplicates share their regular-file offset, so the execution read can
        # observe EOF and return success without running ENTRY.  Feed the exact
        # already-open, descriptor-verified bytes through stdin once instead.
        os.lseek(entry_fd, 0, os.SEEK_SET)
        run = subprocess.run(["/usr/bin/python3", "-I", "-S", "-B", "-", "--repo", str(source),
                              "--contract-fd", str(contract_fd), "--contract-sha256", str(generated["contract"]["sha256"]),
                              "--contract-size", str(generated["contract"]["size"]), "--hosted-receipt", str(authority / "hosted-live-envelope.json"), "--release-candidate", "build",
                              "--print-bin-path"],
                             stdin=entry_fd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
                             pass_fds=(contract_fd,), env={"PATH": "/usr/bin:/bin:/usr/sbin:/sbin", "LC_ALL": "C", "DEVELOPER_DIR": "/Library/Developer/CommandLineTools"}, check=False)
    finally:
        os.close(contract_fd)
        os.close(entry_fd)
    if run.returncode != 0:
        sys.stderr.write(run.stderr)
        deny("held-wrapper-failed: " + str(run.returncode))
    receipt_path = authority / "live-state-retained.receipt"
    if not receipt_path.exists():
        sys.stderr.write(run.stderr)
        try:
            inventory = ",".join(sorted(os.listdir(authority)))
        except OSError:
            inventory = "unavailable"
        sys.stderr.write("hosted-authority-inventory=" + inventory + "\n")
        deny("held-terminal-receipt-missing")
    release_output = retained_release_output(authority)
    # Recheck the candidate after the wrapper and bind the actual retained
    # host-state proof into the build receipt rather than a hash-only claim.
    prepare_recheck(source, authority, policy_path, completed=True)
    retained = {name: descriptor(authority / name, maximum=65536) for name in ("live-state-retained.receipt", "preflight-state.snapshot", "postflight-state.snapshot", "preflight.pmset-assertions", "postflight.pmset-assertions", "hosted-live-envelope.json")}
    print(canonical({"schema": "lidswitch-hosted-build-v2", "source": ledger["source"], "generated": generated,
                     "ledger": descriptor(ledger_path), "entry": descriptor(entry), "contract": descriptor(contract),
                     "retained": retained, "release_output": release_output}).decode(), end="")
    return {"release_output": release_output}


def retained_release_output(authority: Path) -> str:
    receipt_path = authority / "live-state-retained.receipt"
    fd = os.open(receipt_path, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC)
    try:
        raw = read_fd(fd, 65536)
    finally:
        os.close(fd)
    rows: dict[str, str] = {}
    for line in raw.decode("utf-8", "strict").splitlines():
        if "=" not in line:
            deny("invalid-retained-receipt")
        key, value = line.split("=", 1)
        if not key or key in rows:
            deny("invalid-retained-receipt")
        rows[key] = value
    expected = {"schema", "nonce", "outcome", "child_command_exit", "wrapper_exit", "preflight_sha256",
                "postflight_sha256", "host_preserved", "benchmark_published", "error", "capture_identifiers",
                "control_root", "execution_root"}
    if set(rows) != expected or rows["schema"] != "3" or rows["outcome"] != "preserved" or rows["child_command_exit"] != "0" or rows["wrapper_exit"] != "0" or rows["host_preserved"] != "true" or rows["error"] != "none":
        deny("invalid-retained-receipt")
    execution = Path(rows["execution_root"])
    if execution.parent != Path("/private/tmp") or re.fullmatch(r"lidswitch-swift\.[A-Za-z0-9._+-]{1,128}", execution.name) is None:
        deny("held-release-output-path-invalid")
    release_output = execution / "release-output"
    checked_directory(release_output)
    return str(release_output)


def prepare_recheck(source: Path, authority: Path, policy_path: Path, *, completed: bool) -> dict[str, object]:
    policy(policy_path)
    ledger_path = authority / "hosted-authority-ledger.json"
    observed = descriptor(ledger_path, maximum=1024 * 1024)
    raw = Path(ledger_path).read_bytes()
    ledger = json.loads(raw.decode("utf-8"))
    if canonical(ledger) != raw or ledger.get("schema") != "lidswitch-hosted-authority-ledger-v1":
        deny("invalid-authority-ledger")
    if ledger.get("source", {}).get("commit") != SOURCE_COMMIT or ledger.get("source", {}).get("tree") != SOURCE_TREE:
        deny("authority-source-binding-mismatch")
    if checked_directory(source) != ledger["source"]["root"]:
        deny("source-root-replacement-before-build")
    expected_files = AUTHORITY_COMPLETE_FILES if completed else AUTHORITY_INITIAL_FILES
    if checked_authority_root(authority, expected_files) != ledger["generated"]["root"]:
        deny("authority-root-replacement-before-build")
    if git(source, "rev-parse", "HEAD").strip() != SOURCE_COMMIT or git(source, "rev-parse", "HEAD^{tree}").strip() != SOURCE_TREE:
        deny("source-drift-before-build")
    if git(source, "status", "--porcelain=v1", "--untracked-files=all"):
        deny("source-not-clean-before-build")
    _manifest, manifest_sha = verify_manifest(source)
    if manifest_sha != ledger["source"]["manifest_sha256"]:
        deny("source-manifest-drift-before-build")
    if descriptor(Path("/bin/bash"), system=True, maximum=16 * 1024 * 1024) != ledger["system"]["bash"]:
        deny("bash-drift-before-build")
    if descriptor(Path("/usr/bin/python3"), system=True, maximum=64 * 1024 * 1024) != ledger["system"]["python"]:
        deny("python-drift-before-build")
    if descriptor(Path("/Library/Developer/CommandLineTools/usr/bin/swift-frontend"), system=True, maximum=512 * 1024 * 1024) != ledger["system"]["swift_frontend"]:
        deny("swift-frontend-drift-before-build")
    if checked_system_directory_selector(Path("/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk")) != ledger["system"]["sdk_root"]:
        deny("sdk-root-drift-before-build")
    return {"ledger": ledger}


def _open_child_directory(parent_fd: int, name: str) -> int:
    if NAME.fullmatch(name) is None or name.startswith("."):
        deny("unsafe-held-packaging-directory-name")
    fd = os.open(name, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC, dir_fd=parent_fd)
    info = os.fstat(fd)
    if not stat.S_ISDIR(info.st_mode):
        os.close(fd)
        deny("unsafe-held-packaging-directory")
    return fd


def _mkdir_once(parent_fd: int, name: str, mode: int) -> int:
    if NAME.fullmatch(name) is None or name.startswith("."):
        deny("unsafe-held-packaging-directory-name")
    os.mkdir(name, mode, dir_fd=parent_fd)
    os.fsync(parent_fd)
    return _open_child_directory(parent_fd, name)


def _open_relative_leaf(root_fd: int, relative: str) -> int:
    parts = relative.split("/")
    if not parts or any(NAME.fullmatch(part) is None or part.startswith(".") for part in parts):
        deny("unsafe-packaging-source-path")
    parent_fd = os.dup(root_fd)
    try:
        for part in parts[:-1]:
            next_fd = _open_child_directory(parent_fd, part)
            os.close(parent_fd)
            parent_fd = next_fd
        return os.open(parts[-1], os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC, dir_fd=parent_fd)
    finally:
        os.close(parent_fd)


def _write_once(parent_fd: int, name: str, data: bytes, mode: int) -> None:
    fd = os.open(name, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW | os.O_CLOEXEC, mode, dir_fd=parent_fd)
    try:
        offset = 0
        while offset < len(data):
            offset += os.write(fd, data[offset:])
        os.fsync(fd)
    finally:
        os.close(fd)
    os.fsync(parent_fd)


def _copy_verified(source_root_fd: int, relative: str, expected: dict[str, object], target_parent_fd: int, target_name: str, target_mode: int) -> None:
    """Verify and copy from one source descriptor; never reopen it by path."""
    fd = _open_relative_leaf(source_root_fd, relative)
    try:
        info = os.fstat(fd)
        data = read_fd(fd, 256 * 1024 * 1024)
        actual = {"path": relative, "dev": info.st_dev, "inode": info.st_ino, "uid": info.st_uid, "gid": info.st_gid, "mode": stat.S_IMODE(info.st_mode), "nlink": info.st_nlink, "size": info.st_size, "sha256": sha256(data)}
        if actual != expected:
            deny("packaging-role-drift: " + relative)
    finally:
        os.close(fd)
    _write_once(target_parent_fd, target_name, data, target_mode)


def _private_directory_record(fd: int, *, mode: int) -> dict[str, object]:
    info = os.fstat(fd)
    if (not stat.S_ISDIR(info.st_mode) or info.st_uid != os.getuid() or info.st_gid != os.getgid() or
            stat.S_IMODE(info.st_mode) != mode or info.st_mode & 0o022 or info.st_nlink < 2):
        deny("unsafe-held-packaging-directory")
    return {"dev": info.st_dev, "inode": info.st_ino, "uid": info.st_uid, "gid": info.st_gid,
            "mode": stat.S_IMODE(info.st_mode), "nlink": info.st_nlink, "size": info.st_size}


def _private_leaf_record(parent_fd: int, name: str, *, mode: int) -> dict[str, object]:
    if NAME.fullmatch(name) is None or name.startswith("."):
        deny("unsafe-held-packaging-leaf-name")
    fd = os.open(name, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC, dir_fd=parent_fd)
    try:
        info = os.fstat(fd)
        if (not stat.S_ISREG(info.st_mode) or info.st_uid != os.getuid() or info.st_gid != os.getgid() or
                info.st_nlink != 1 or stat.S_IMODE(info.st_mode) != mode or info.st_mode & 0o022):
            deny("unsafe-held-packaging-leaf")
        data = read_fd(fd, 256 * 1024 * 1024)
        return {"dev": info.st_dev, "inode": info.st_ino, "uid": info.st_uid, "gid": info.st_gid,
                "mode": stat.S_IMODE(info.st_mode), "nlink": info.st_nlink, "size": info.st_size,
                "sha256": sha256(data)}
    finally:
        os.close(fd)


def _read_authority_descriptor(path: Path, expected: dict[str, object]) -> bytes:
    fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC)
    try:
        info = os.fstat(fd)
        data = read_fd(fd, 1024 * 1024)
        actual = {"path": str(path), "dev": info.st_dev, "inode": info.st_ino, "uid": info.st_uid, "gid": info.st_gid, "mode": stat.S_IMODE(info.st_mode), "nlink": info.st_nlink, "size": info.st_size, "sha256": sha256(data)}
        if actual != expected:
            deny("packaging-contract-authority-drift")
        return data
    finally:
        os.close(fd)


def _exact_inventory(directory_fd: int, expected: set[str]) -> None:
    observed = os.listdir(directory_fd)
    if any(name.startswith(".") or NAME.fullmatch(name) is None for name in observed) or set(observed) != expected:
        deny("held-packaging-inventory-drift")


def _sealed_package_closure(root: Path, names: dict[str, str] = PACKAGING_SCRIPTS) -> dict[str, dict[str, dict[str, object]]]:
    """Return complete held-root, directory, and leaf closure metadata.

    Every path below ``root`` is opened relative to a retained no-follow
    directory descriptor.  The result deliberately includes directories,
    leaves, ownership, modes, link counts, sizes, and content hashes so a
    pre/post child check catches any observable closure replacement.
    """
    if set(names) != set(PACKAGING_SCRIPTS) or names != PACKAGING_SCRIPTS:
        deny("held-packaging-role-inventory-drift")
    root_fd = os.open(root, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC)
    try:
        root_record = _private_directory_record(root_fd, mode=0o500)
        _exact_inventory(root_fd, {"script", "Resources"})
        script_fd = _open_child_directory(root_fd, "script")
        resources_fd = _open_child_directory(root_fd, "Resources")
        try:
            script_record = _private_directory_record(script_fd, mode=0o500)
            resources_record = _private_directory_record(resources_fd, mode=0o500)
            _exact_inventory(script_fd, set(PACKAGING_SCRIPTS.values()))
            _exact_inventory(resources_fd, set(PACKAGING_RESOURCES.values()))
            leaves: dict[str, dict[str, object]] = {}
            for name in sorted(PACKAGING_SCRIPTS.values()):
                leaves["script/" + name] = _private_leaf_record(
                    script_fd, name, mode=0o500 if name in PACKAGING_ENTRYPOINTS else 0o400)
            for name in sorted(PACKAGING_RESOURCES.values()):
                leaves["Resources/" + name] = _private_leaf_record(resources_fd, name, mode=0o400)
            return {"directories": {"root": root_record, "script": script_record, "Resources": resources_record},
                    "leaves": leaves}
        finally:
            os.close(resources_fd)
            os.close(script_fd)
    finally:
        os.close(root_fd)


def _require_sealed_package_closure(root: Path, names: dict[str, str], expected: dict[str, dict[str, dict[str, object]]]) -> None:
    if _sealed_package_closure(root, names) != expected:
        deny("held-packaging-closure-drift")


def _audit_packaging_modules(root: Path) -> list[str]:
    """Reject a local import that is outside the held script closure."""
    allowed = {name[:-3] for name in PACKAGING_SCRIPTS.values() if name.endswith(".py")}
    observed: set[str] = set()
    for filename in allowed:
        source = (root / "script" / (filename + ".py")).read_text("utf-8")
        for node in ast.walk(ast.parse(source, filename=filename)):
            module = None
            if isinstance(node, ast.Import):
                for item in node.names:
                    module = item.name.split(".", 1)[0]
                    if module in allowed:
                        observed.add(module)
            elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
                module = node.module.split(".", 1)[0]
                if module in allowed:
                    observed.add(module)
    return sorted(observed)


def _run_sealed_packaging(entry: Path, held: Path, allowed_modules: list[str], arguments: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["/usr/bin/python3", "-I", "-S", "-B", "-c", PACKAGING_PYTHON_BOOTSTRAP,
         str(entry), str(held / "script"), json.dumps(allowed_modules, sort_keys=True), *arguments],
        stdin=subprocess.DEVNULL, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
        env=PACKAGING_ENV, cwd="/", check=False)


def package(source: Path, authority: Path, policy_path: Path, release_output: Path, package_parent: Path) -> dict[str, object]:
    prepared = prepare_recheck(source, authority, policy_path, completed=True)
    contract_path = authority / "hosted-held-contract.json"
    raw_contract = _read_authority_descriptor(contract_path, prepared["ledger"]["generated"]["contract"])
    contract = json.loads(raw_contract.decode("utf-8"))
    if canonical(contract) != raw_contract or contract.get("source_manifest") != prepared["ledger"]["source"]["manifest_descriptor"]["sha256"]:
        deny("packaging-contract-invalid")
    held = package_parent / "held-packaging"
    if held.exists() or held.is_symlink() or package_parent.is_symlink():
        deny("unsafe-held-packaging-root")
    package_parent_fd = os.open(package_parent, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC)
    source_fd = os.open(source, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC)
    try:
        held_fd = _mkdir_once(package_parent_fd, "held-packaging", 0o700)
        try:
            script_fd = _mkdir_once(held_fd, "script", 0o700)
            resources_fd = _mkdir_once(held_fd, "Resources", 0o700)
            try:
                for role, name in PACKAGING_SCRIPTS.items():
                    _copy_verified(source_fd, contract["roles"][role]["path"], contract["roles"][role], script_fd, name,
                                   0o500 if name in PACKAGING_ENTRYPOINTS else 0o400)
                for role, name in PACKAGING_RESOURCES.items():
                    _copy_verified(source_fd, contract["roles"][role]["path"], contract["roles"][role], resources_fd, name, 0o400)
                os.fchmod(script_fd, 0o500)
                os.fchmod(resources_fd, 0o500)
                os.fsync(script_fd)
                os.fsync(resources_fd)
            finally:
                os.close(resources_fd)
                os.close(script_fd)
            os.fchmod(held_fd, 0o500)
            os.fsync(held_fd)
        finally:
            os.close(held_fd)
    finally:
        os.close(source_fd)
        os.close(package_parent_fd)
    names = PACKAGING_SCRIPTS
    allowed_modules = _audit_packaging_modules(held)
    closure = _sealed_package_closure(held, names)
    envelope = package_parent / "build-envelope.json"
    command = ["/usr/bin/python3", "-I", "-S", "-B", str(held / "script/capture_immutable_build_envelope.py"), "--source-commit", SOURCE_COMMIT, "--source-manifest", str(held / "script/source_snapshot_manifest.jsonl"), "--held-build-wrapper", str(held / "script/run_swift_build_safely.sh"), "--swift", "/Library/Developer/CommandLineTools/usr/bin/swift", "--release-output", str(release_output), "--output", str(envelope)]
    _require_sealed_package_closure(held, names, closure)
    first = _run_sealed_packaging(held / "script/capture_immutable_build_envelope.py", held, allowed_modules, command[5:])
    if first.returncode:
        sys.stderr.write(first.stderr); deny("held-packaging-capture-failed")
    _require_sealed_package_closure(held, names, closure)
    candidate = package_parent / "candidate"
    _require_sealed_package_closure(held, names, closure)
    second = _run_sealed_packaging(held / "script/assemble_manual_adhoc_candidate.py", held, allowed_modules, ["--envelope-receipt", str(envelope), "--release-output", str(release_output), "--output-root", str(candidate), "--icon", str(held / "Resources/LidSwitch.icns"), "--release-identity", str(held / "Resources/LidSwitchReleaseIdentity.json")])
    if second.returncode:
        sys.stderr.write(second.stderr); deny("held-packaging-assemble-failed")
    _require_sealed_package_closure(held, names, closure)
    prepare_recheck(source, authority, policy_path, completed=True)
    return {"schema": "lidswitch-hosted-package-v1", "package_parent": str(package_parent), "candidate_root": str(candidate), "envelope": descriptor(envelope), "held_packaging": closure}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(allow_abbrev=False)
    sub = parser.add_subparsers(dest="command", required=True)
    for name in ("prepare", "build", "package"):
        item = sub.add_parser(name, allow_abbrev=False)
        item.add_argument("--source", required=True, type=Path)
        item.add_argument("--authority", required=True, type=Path)
        item.add_argument("--policy", required=True, type=Path)
        if name == "build":
            for role in ("ledger", "entry", "contract"):
                item.add_argument("--expected-" + role + "-sha256", required=True)
                item.add_argument("--expected-" + role + "-size", required=True, type=int)
        if name == "package":
            item.add_argument("--release-output", required=True, type=Path)
            item.add_argument("--package-parent", required=True, type=Path)
    args = parser.parse_args(argv)
    try:
        if args.command == "prepare":
            print(canonical(prepare(args.source, args.authority, args.policy)).decode(), end="")
        elif args.command == "build":
            build(args.source, args.authority, args.policy, {role: (getattr(args, "expected_" + role + "_sha256"), getattr(args, "expected_" + role + "_size")) for role in ("ledger", "entry", "contract")})
        else:
            print(canonical(package(args.source, args.authority, args.policy, args.release_output, args.package_parent)).decode(), end="")
        return 0
    except (Denied, OSError, UnicodeError, json.JSONDecodeError, KeyError, TypeError) as error:
        print("hosted-held-bootstrap-denied: " + str(error), file=sys.stderr)
        return EX_IOERR


if __name__ == "__main__":
    raise SystemExit(main())
